In [1]:
from sqlalchemy import create_engine,text
import pandas as pd
import os

In [2]:
engine1 = create_engine ("mysql+pymysql://piuser:Pass%40123@localhost:3306/piit")
print(engine1)

Engine(mysql+pymysql://piuser:***@localhost:3306/piit)

In [3]:
def q(sql,**params):
    with engine1.connect () as conn:
        return pd.read_sql(text(sql),conn,params=params)

In [6]:
q("show databases")

             Database
0  information_schema
1  performance_schema
2                piit

In [9]:
q("show tables")

       Tables_in_piit
0             authors
1               books
2           crimedata
3         departments
4   employee_earnings
5           employees
6              evdata
7      exceldatafile1
8              mtcars
9            obisdata
10         piitstdata
11           students
12          students2
13              team1

In [10]:
q("select * from departments limit 10")

   department_id department_name studentsqty
0              1              HR        None
1              2     Engineering        None
2              3       Marketing        None
3              4         Finance        None

In [11]:
q("select * from piitstdata limit 10")

  rollno  english  maths  python
0   P100       79     75      66
1   P101       71     56      91
2   P102       62     69      78
3   P103       63     57      70
4   P104       81     52      98
5   P105       85     70      94
6   P106       94     60      85
7   P107       93     84      67
8   P108       59     81      61
9   P109       70     97      86

In [19]:
q("select * from piitstdata")

   rollno  english  maths  python
0    P100       79     75      66
1    P101       71     56      91
2    P102       62     69      78
3    P103       63     57      70
4    P104       81     52      98
5    P105       85     70      94
6    P106       94     60      85
7    P107       93     84      67
8    P108       59     81      61
9    P109       70     97      86
10   P110       73     91      50
11   P111       70     89      64
12   P112       77     66      78
13   P113       71     70      81
14   P123       69     75      50

In [20]:
q("select rollno from piitstdata where maths> 60")

   rollno
0    P100
1    P102
2    P105
3    P107
4    P108
5    P109
6    P110
7    P111
8    P112
9    P113
10   P123

In [23]:
q("select rollno from piitstdata where maths> 60 and python > 90")

  rollno
0   P105

In [24]:
q("select * from students2")

    rollno        name  gender         dob  height program
0        1    Jugurtha    Male  2000-08-16     156     BCA
1        2    Amandeep  Female  2000-02-21     170     BBA
2        3      Barkat  Female  2001-07-17     158     BCA
3        4      Suroor  Female  2001-11-16     188     BBA
4        5     Sultana    Male  2001-04-02     167     BCA
5        6      Sajjad    Male  2000-10-12     153     BCA
6        7      Sharan    Male  2000-07-28     174     BBA
7        8    Djedjiga  Female  2000-06-27     163     BCA
8        9      Bijata  Female  2002-05-14     158     BBA
9       10      Mahadi  Female  2000-03-06     175     BCA
10      11      Sundas    Male  2000-03-02     151     BCA
11      12      Mandal    Male  2000-07-10     169     BBA
12      13      Najmul  Female  2001-03-23     177     BCA
13      14       Deniz    Male  2001-04-21     156     BBA
14      15     Sharmin    Male  2002-10-31     157     BCA
15      16       Emran    Male  2000-02-24     184     BBA
16      17      Sundas    Male  2001-02-11     163     BBA
17      18     Tanzeel  Female  2002-05-09     166     BCA
18      19  Student_19    Male  2001-03-27     185     BCA
19      20  Student_20    Male  2002-07-08     189     BBA
20      21  Student_21  Female  2001-07-23     153     BCA
21      22  Student_22    Male  2000-01-14     151     BCA
22      23  Student_23    Male  2000-11-22     155     BCA
23      24  Student_24    None  2002-05-15     153     BBA
24      25  Student_25  Female  2001-11-27     178     BBA
25      26  Student_26    None  2001-07-23     167     BBA
26      27  Student_27    Male  2000-11-14     175     BBA
27      28  Student_28  Female  2001-03-16     183     BBA
28      29  Student_29  Female  2001-11-20     159     BBA
29      30  Student_30    Male  2000-07-28     185     BBA

In [32]:
q("SELECT name from students2 where program='BBA'")

          name
0     Amandeep
1       Suroor
2       Sharan
3       Bijata
4       Mandal
5        Deniz
6        Emran
7       Sundas
8   Student_20
9   Student_24
10  Student_25
11  Student_26
12  Student_27
13  Student_28
14  Student_29
15  Student_30

In [35]:
q("SELECT name,gender from students2 where program='BBA'")

          name  gender
0     Amandeep  Female
1       Suroor  Female
2       Sharan    Male
3       Bijata  Female
4       Mandal    Male
5        Deniz    Male
6        Emran    Male
7       Sundas    Male
8   Student_20    Male
9   Student_24    None
10  Student_25  Female
11  Student_26    None
12  Student_27    Male
13  Student_28  Female
14  Student_29  Female
15  Student_30    Male

In [37]:
q("SELECT name,gender from students2 where program='BBA' limit 5")

       name  gender
0  Amandeep  Female
1    Suroor  Female
2    Sharan    Male
3    Bijata  Female
4    Mandal    Male

In [38]:
q("show tables")

       Tables_in_piit
0             authors
1               books
2           crimedata
3         departments
4   employee_earnings
5           employees
6              evdata
7      exceldatafile1
8              mtcars
9            obisdata
10         piitstdata
11           students
12          students2
13              team1

In [39]:
q("SELECT * FROM evdata limit 10")

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,WA1E2AFY8R,Thurston,Olympia,WA,98512.0,2024,AUDI,Q5 E,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,23.0,0.0,22.0,263239938,POINT (-122.90787 46.9461),PUGET SOUND ENERGY INC,5.306701e+10
1,WAUUPBFF4J,Yakima,Wapato,WA,98951.0,2018,AUDI,A3,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,16.0,0.0,15.0,318160860,POINT (-120.42083 46.44779),PACIFICORP,5.307794e+10
2,1N4AZ0CP0F,King,Seattle,WA,98125.0,2015,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,84.0,0.0,46.0,184963586,POINT (-122.30253 47.72656),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303300e+10
3,WA1VAAGE5K,King,Kent,WA,98031.0,2019,AUDI,E-TRON,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,204.0,0.0,11.0,259426821,POINT (-122.17743 47.41185),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303303e+10
4,7SAXCAE57N,Snohomish,Bothell,WA,98021.0,2022,TESLA,MODEL X,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,0.0,1.0,208182236,POINT (-122.18384 47.8031),PUGET SOUND ENERGY INC,5.306105e+10
5,KNDJP3AEXG,Snohomish,Lynnwood,WA,98037.0,2016,KIA,SOUL,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,93.0,31950.0,21.0,209171889,POINT (-122.27734 47.83785),PUGET SOUND ENERGY INC,5.306105e+10
6,1N4AZ1CP7K,Snohomish,Edmonds,WA,98026.0,2019,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,150.0,0.0,32.0,478448624,POINT (-122.31768 47.87166),PUGET SOUND ENERGY INC,5.306105e+10
7,KNDCC3LG4L,Snohomish,Brier,WA,98036.0,2020,KIA,NIRO,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,239.0,0.0,1.0,281365724,POINT (-122.29245 47.82557),PUGET SOUND ENERGY INC,5.306105e+10
8,KM8JFDD27S,Kitsap,Bremerton,WA,98311.0,2025,HYUNDAI,TUCSON,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,32.0,0.0,23.0,281377456,POINT (-122.60915 47.62631),PUGET SOUND ENERGY INC,5.303509e+10
9,1C4JJXR6XM,Sauk,Spring Green,WI,53588.0,2021,JEEP,WRANGLER,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,21.0,0.0,NaN,182273605,POINT (-90.06403 43.17838),NON WASHINGTON STATE ELECTRIC UTILITY,5.511100e+10