In [1]:
import pandas as pd
import numpy as np

In [4]:
data = pd.read_csv(r"C:\analytics\data\mtcars.csv")

In [17]:
data.dtypes #data types

model           object
mpg            float64
cyl              int64
disp           float64
hp               int64
drat           float64
wt             float64
qsec           float64
vs               int64
am               int64
gear             int64
carb             int64
Unnamed: 12    float64
dtype: object

In [5]:
data.head(10)

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,Unnamed: 12
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,NaN
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,NaN
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,NaN
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,NaN
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,NaN
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,NaN
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,NaN
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,NaN
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,NaN
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,NaN

In [6]:
data.head()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,Unnamed: 12
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,NaN
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,NaN
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,NaN
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,NaN
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,NaN

In [9]:
data.shape #to show total number of rows & columns

(32, 13)

In [12]:
data.index

RangeIndex(start=0, stop=32, step=1)

In [14]:
data.columns # coloumn names

Index(['model', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am',
       'gear', 'carb', 'Unnamed: 12'],
      dtype='object')

In [20]:
data["model"].unique()

array(['Mazda RX4', 'Mazda RX4 Wag', 'Datsun 710', 'Hornet 4 Drive',
       'Hornet Sportabout', 'Valiant', 'Duster 360', 'Merc 240D',
       'Merc 230', 'Merc 280', 'Merc 280C', 'Merc 450SE', 'Merc 450SL',
       'Merc 450SLC', 'Cadillac Fleetwood', 'Lincoln Continental',
       'Chrysler Imperial', 'Fiat 128', 'Honda Civic', 'Toyota Corolla',
       'Toyota Corona', 'Dodge Challenger', 'AMC Javelin', 'Camaro Z28',
       'Pontiac Firebird', 'Fiat X1-9', 'Porsche 914-2', 'Lotus Europa',
       'Ford Pantera L', 'Ferrari Dino', 'Maserati Bora', 'Volvo 142E'],
      dtype=object)

In [24]:
data["model"].nunique()

32

In [25]:
data.nunique()

model          32
mpg            25
cyl             3
disp           27
hp             22
drat           22
wt             29
qsec           30
vs              2
am              2
gear            3
carb            6
Unnamed: 12     0
dtype: int64

In [26]:
data.count()

model          32
mpg            32
cyl            32
disp           32
hp             32
drat           32
wt             32
qsec           32
vs             32
am             32
gear           32
carb           32
Unnamed: 12     0
dtype: int64

In [27]:
data["mpg"].value_counts()

mpg
21.0    2
22.8    2
21.4    2
19.2    2
10.4    2
15.2    2
30.4    2
18.1    1
18.7    1
17.8    1
24.4    1
14.3    1
17.3    1
16.4    1
14.7    1
32.4    1
33.9    1
21.5    1
15.5    1
13.3    1
27.3    1
26.0    1
15.8    1
19.7    1
15.0    1
Name: count, dtype: int64

In [28]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   model        32 non-null     object
 1   mpg          32 non-null     float64
 2   cyl          32 non-null     int64
 3   disp         32 non-null     float64
 4   hp           32 non-null     int64
 5   drat         32 non-null     float64
 6   wt           32 non-null     float64
 7   qsec         32 non-null     float64
 8   vs           32 non-null     int64
 9   am           32 non-null     int64
 10  gear         32 non-null     int64
 11  carb         32 non-null     int64
 12  Unnamed: 12  0 non-null      float64
dtypes: float64(6), int64(6), object(1)
memory usage: 3.4+ KB

In [29]:
# find number of unique values in a column

In [30]:
data.nunique()

model          32
mpg            25
cyl             3
disp           27
hp             22
drat           22
wt             29
qsec           30
vs              2
am              2
gear            3
carb            6
Unnamed: 12     0
dtype: int64

In [31]:
data["mpg"].nunique()

25

In [32]:
data["mpg"].unique()

array([21. , 22.8, 21.4, 18.7, 18.1, 14.3, 24.4, 19.2, 17.8, 16.4, 17.3,
       15.2, 10.4, 14.7, 32.4, 30.4, 33.9, 21.5, 15.5, 13.3, 27.3, 26. ,
       15.8, 19.7, 15. ])