In [1]:
##IQR,OUTLIERS

In [2]:
import pandas as pd
import numpy as np

In [3]:
x5=[10,20,30,40,50,60,70]
#25th,50th (median), and precentiles
q25=np.quantile(x5,0.25)#q1
q50=np.quantile(x5,0.5)#q2
q75=np.quantile(x5,0.75)#q3
print(q25,q50,q75)

25.0 40.0 55.0

In [4]:
import statistics as stats
stats.median(x5)#40
stats.quantiles(x5,n=4) # quantiles

[20.0, 40.0, 60.0]

In [10]:
from pydataset import data

df = data('mtcars')
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [11]:
df.describe()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [12]:
df.describe(include='all').loc[['min','25%','50%','75%','max']]

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
min,10.400,4.0,71.100,52.0,2.760,1.51300,14.5000,0.0,0.0,3.0,1.0
25%,15.425,4.0,120.825,96.5,3.080,2.58125,16.8925,0.0,0.0,3.0,2.0
50%,19.200,6.0,196.300,123.0,3.695,3.32500,17.7100,0.0,0.0,4.0,2.0
75%,22.800,8.0,326.000,180.0,3.920,3.61000,18.9000,1.0,1.0,4.0,4.0
max,33.900,8.0,472.000,335.0,4.930,5.42400,22.9000,1.0,1.0,5.0,8.0

In [13]:
from scipy import stats
import numpy as np

In [19]:
x6= np.array([10,20,30,40,50,60,70])
q25, q50, q75 = np.percentile(x6,[25,50,75], method='linear')
print(q25,q50,q75)

25.0 40.0 55.0

In [22]:
np.quantile(x6, [0.25, 0.5, 0.75], method='midpoint')

array([25., 40., 55.])

In [24]:
##IQR (DIFFERENCE OF Q3 & Q1)

In [26]:
x7=[10,20,30,40,50,60,70]
Q1 = np.percentile(x7,25)
Q3 = np.percentile(x7,75)
IQR = Q3-Q1
print(x7,"\n Q1:", Q1,"Q3", Q3,"IQR", IQR)

[10, 20, 30, 40, 50, 60, 70]
 Q1: 25.0 Q3 55.0 IQR 30.0

In [27]:
from scipy.stats import iqr
import  numpy as np

In [29]:
x7B = np.array([10,20,30,40,50,60,70])
IQR = iqr(x7B)
print(x7B,"\n IQR", IQR)

[10 20 30 40 50 60 70]
 IQR 30.0

In [33]:
import statistics as stats

x7c = [10, 20, 30, 40, 50, 60, 70]

# Quartiles: Q1 = q[0], Q2 = q[1], Q3 = q[2]
q = stats.quantiles(x7c, n=4)

# IQR = Q3 - Q1
IQR = q[2] - q[0]

print(x7c, "\nQ3:", q[2], "Q1:", q[0], ":: IQR:", IQR)

[10, 20, 30, 40, 50, 60, 70]
Q3: 60.0 Q1: 20.0 :: IQR: 40.0

In [34]:
# OUTLIERS

In [37]:
X8=[-100,10,20,30,40,50,60,70,1000]

In [38]:
Q1 =np.percentile(x8,25)
Q3 =np.percentile(x8,50)
IQR = Q3-Q1
lower_drber

NameError: name 'x8' is not defined