In [1]:
import numpy as np
import pandas as pd
from pydataset import data
import os
import matplotlib.pyplot as plt
import random
import seaborn as sns

####RANDOM

In [2]:
print(random.random())  #any random value 0 and 1

0.3694926643440961

In [3]:
random.randint(10, 100)  #any random integer between 10 and 100

98

In [4]:
random.randrange(11, 35, 2) #random even no between 11 and 35

27

In [5]:
my_list = ['apple', 'banana', 'cherry']
random.choice(my_list)

'cherry'

In [6]:
my_list = [1, 2, 3, 4, 5]
random.shuffle(my_list)
print(my_list)

[1, 2, 5, 3, 4]

In [7]:
random.sample(['red', 'blue'], counts=[6, 2], k=8)  #create 4 values of red, 2 values of blue, in random order; total 5

['red', 'red', 'red', 'red', 'blue', 'red', 'red', 'blue']

In [8]:
random.sample(['Nayeema', 'Huma', 'Ratiba', 'Mohammad'], k=3)  # without replacement

['Nayeema', 'Ratiba', 'Mohammad']

In [9]:
random.choices(['HR', 'IT'], k=3) # with replacement

['HR', 'IT', 'IT']

# I have school of 1000 students, I want to pickup only 10 students (without replacement) and allot them 3 projects (with replacement)

In [10]:
df = data('mtcars')
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [11]:
df.dtypes

mpg     float64
cyl       int64
disp    float64
hp        int64
drat    float64
wt      float64
qsec    float64
vs        int64
am        int64
gear      int64
carb      int64
dtype: object

In [12]:
df.describe()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [13]:
mpgvalues = df.mpg.sort_values().to_list() 
mpgvalues[0], mpgvalues[8], mpgvalues[16] , mpgvalues[24], mpgvalues[31]  #16,24,32]]  #32 : min(0), max(32), 25% (32/4=8), 50%(16), 75%(24)

(10.4, 15.5, 19.2, 22.8, 33.9)

In [14]:
Functions1
mean
median
mode
image.png

NameError: name 'Functions1' is not defined

In [15]:
df.mean(axis=0) #mean each co

mpg      20.090625
cyl       6.187500
disp    230.721875
hp      146.687500
drat      3.596563
wt        3.217250
qsec     17.848750
vs        0.437500
am        0.406250
gear      3.687500
carb      2.812500
dtype: float64

In [16]:
df.mean(axis=1).head() #mean each row

Mazda RX4            29.907273
Mazda RX4 Wag        29.981364
Datsun 710           23.598182
Hornet 4 Drive       38.739545
Hornet Sportabout    53.664545
dtype: float64

In [17]:
df.median(axis=0)

mpg      19.200
cyl       6.000
disp    196.300
hp      123.000
drat      3.695
wt        3.325
qsec     17.710
vs        0.000
am        0.000
gear      4.000
carb      2.000
dtype: float64

In [18]:
x = [1,2,3,3,4,5]
x

[1, 2, 3, 3, 4, 5]

In [19]:
np.median(x)

np.float64(3.0)

In [20]:
random.shuffle(x)
x

[4, 5, 1, 3, 2, 3]

In [21]:
np.median(x)

np.float64(3.0)

###MODE - max freq

In [22]:
from scipy import stats

In [23]:
df.mode() #pandas mode
# categorical cols - am, vs, carb, gear, cyl
# numerical cols - mpg, wt, hp, drat, qsec, disp

    mpg  cyl   disp     hp  drat    wt   qsec   vs   am  gear  carb
0  10.4  8.0  275.8  110.0  3.07  3.44  17.02  0.0  0.0   3.0   2.0
1  15.2  NaN    NaN  175.0  3.92   NaN  18.90  NaN  NaN   NaN   4.0
2  19.2  NaN    NaN  180.0   NaN   NaN    NaN  NaN  NaN   NaN   NaN
3  21.0  NaN    NaN    NaN   NaN   NaN    NaN  NaN  NaN   NaN   NaN
4  21.4  NaN    NaN    NaN   NaN   NaN    NaN  NaN  NaN   NaN   NaN
5  22.8  NaN    NaN    NaN   NaN   NaN    NaN  NaN  NaN   NaN   NaN
6  30.4  NaN    NaN    NaN   NaN   NaN    NaN  NaN  NaN   NaN   NaN

In [24]:
df.gear.value_counts()

gear
3    15
4    12
5     5
Name: count, dtype: int64

In [25]:
df.carb.value_counts()

carb
4    10
2    10
1     7
3     3
6     1
8     1
Name: count, dtype: int64

In [26]:
df.cyl.mode()

0    8
Name: cyl, dtype: int64

In [27]:
df.cyl.value_counts()

cyl
8    14
4    11
6     7
Name: count, dtype: int64

In [28]:
import statistics as stats  #note same module in scipy
x1 = [1, 2, 2, 3, 4, 4, 4, 5,5,5,5]
x1

[1, 2, 2, 3, 4, 4, 4, 5, 5, 5, 5]

In [29]:
max(set(x1), key= x1.count)

5

In [30]:
print('Mode of list is ', stats.mode(x1))  # error if tie, more than 1 mode
Mode of list is  5

SyntaxError: invalid syntax (1528507528.py, line 2)

In [31]:
print('Mode of list is ', stats.mode(x1)

_IncompleteInputError: incomplete input (4156820140.py, line 1)

In [32]:
print('Multi Mode of list is ', stats.multimode(x1))

Multi Mode of list is  [5]

In [33]:
x2 = [1,1,2,2,3]
print(x2, ' : Multi Mode of list is ', stats.multimode(x2))

[1, 1, 2, 2, 3]  : Multi Mode of list is  [1, 2]

Functions2
min
max
range
count
quantile/ quartile
IQR
std
var

In [34]:
df.(head)

SyntaxError: invalid syntax (2128476482.py, line 1)

In [36]:
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [37]:
df.describe()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [39]:
df[['mpg','wt']].max() #default axis=0##max

mpg    33.900
wt      5.424
dtype: float64

In [40]:
df[['mpg','wt']].min(axis=0)##min

mpg    10.400
wt      1.513
dtype: float64

In [41]:
df[['mpg','wt']].max() - df[['mpg','wt']].min()####range

mpg    23.500
wt      3.911
dtype: float64

In [42]:
x3 = np.array([4, 8, 15, 16, 23, 42])
x3

array([ 4,  8, 15, 16, 23, 42])

In [43]:
df.apply(lambda col: col.max() - col.min()) #pandas

mpg      23.500
cyl       4.000
disp    400.900
hp      283.000
drat      2.170
wt        3.911
qsec      8.400
vs        1.000
am        1.000
gear      2.000
carb      7.000
dtype: float64

In [44]:
x4 = [1, 2, 2, 3, 3, 3, 4]
print(x4.count(4))   # Output: 3   ####count

1

In [46]:
from collections import Counter
x4 = [1, 2, 2, 2, 3, 3, 3, 3, 4, 5, 5, 5,5,5]
counts = Counter(x4)
print(counts)

Counter({5: 5, 3: 4, 2: 3, 1: 1, 4: 1})

In [47]:
# most common TWO items
counts.most_common(2)

[(5, 5), (3, 4)]

In [48]:
counts.most_common(1) # highest

[(5, 5)]

In [50]:
df.describe().head(1)

        mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
count  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0

In [51]:
df.count()

mpg     32
cyl     32
disp    32
hp      32
drat    32
wt      32
qsec    32
vs      32
am      32
gear    32
carb    32
dtype: int64

In [52]:
x5 = [10, 20, 30, 40, 50, 60, 70]

# 25th, 50th (median), and 75th percentiles
q25 = np.quantile(x5, 0.25)
q50 = np.quantile(x5, 0.5)
q75 = np.quantile(x5, 0.75)
print(q25, q50, q75)

25.0 40.0 55.0

In [53]:
df.describe()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [54]:
df.describe(include='all').loc[['min','25%','50%','75%','max']]

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
min,10.400,4.0,71.100,52.0,2.760,1.51300,14.5000,0.0,0.0,3.0,1.0
25%,15.425,4.0,120.825,96.5,3.080,2.58125,16.8925,0.0,0.0,3.0,2.0
50%,19.200,6.0,196.300,123.0,3.695,3.32500,17.7100,0.0,0.0,4.0,2.0
75%,22.800,8.0,326.000,180.0,3.920,3.61000,18.9000,1.0,1.0,4.0,4.0
max,33.900,8.0,472.000,335.0,4.930,5.42400,22.9000,1.0,1.0,5.0,8.0

####PERCENTILE

In [56]:
from scipy import stats
import numpy as np

x6 = np.array([10, 20, 30, 40, 50, 60, 70])
q25, q50, q75 = np.percentile(x6, [25, 50, 75], method='linear')
print(q25, q50, q75)

25.0 40.0 55.0

In [57]:
np.quantile(x6, [0.25, 0.5, 0.75], method='midpoint')
#Different method options (e.g., 'linear', 'lower', 'higher', 'midpoint', 'nearest') 
#change how quantiles are interpolated.

array([25., 40., 55.])

In [ ]:
####END PRACTICE