In [2]:
import pandas as pd
import pymysql
from sqlalchemy import create_engine
import os

In [3]:
file_path = 'C:/analytics/data/exceldatafile1.csv'
print(file_path)

C:/analytics/data/exceldatafile1.csv

In [4]:
df=pd.read_csv(file_path)

In [5]:
df.head()

,StudentID,FirstName,LastName,Gender,Class,AdmissionDate,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,S001,Aarav,Sharma,M,12A,2024-04-15,NaN,ASSIGN 1,NaN,NaN,NaN,NaN,Concatinate
1,S002,Vivaan,Verma,F,12A,2024-04-21,NaN,StudentID,FirstName,LastName,NaN,NaN,Aarav Sharma
2,S003,Aditya,Gupta,M,12A,2024-05-19,NaN,S001,Aarav,Sharma,NaN,NaN,Vivaan Verma
3,S004,Vihaan,Mehta,M,12C,2024-06-11,NaN,S002,Vivaan,Verma,NaN,NaN,Aditya Gupta
4,S005,Arjun,Singh,M,12C,2022-06-22,NaN,S0007,NOTFOUND,NOTFOUND,IFERROR,NaN,Vihaan Mehta

In [6]:
#engine = create_engine('mysql+pymysql://piuser:Pass#123@localhost:3306/piit')
engine1 = create_engine("mysql+pymysql://piuser:Pass%40123@localhost:3306/piit")
engine1

Engine(mysql+pymysql://piuser:***@localhost:3306/piit)

In [7]:
df.to_sql('exceldatafile1', engine1, if_exists='append', index=False, chunksize=1000, method='multi')

40

In [8]:
df2 = pd.read_sql("SELECT * FROM exceldatafile1;", engine1)
df2.head()

,StudentID,FirstName,LastName,Gender,Class,AdmissionDate,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,S001,Aarav,Sharma,M,12A,2024-04-15,None,ASSIGN 1,None,None,None,None,Concatinate
1,S002,Vivaan,Verma,F,12A,2024-04-21,None,StudentID,FirstName,LastName,None,None,Aarav Sharma
2,S003,Aditya,Gupta,M,12A,2024-05-19,None,S001,Aarav,Sharma,None,None,Vivaan Verma
3,S004,Vihaan,Mehta,M,12C,2024-06-11,None,S002,Vivaan,Verma,None,None,Aditya Gupta
4,S005,Arjun,Singh,M,12C,2022-06-22,None,S0007,NOTFOUND,NOTFOUND,IFERROR,None,Vihaan Mehta

In [9]:
df2.to_csv('C:/analytics/data/exceldatafile2.csv')

In [11]:
df2.to_excel('C:/analytics/data/exceldatafile2.xlsx')