In [9]:
from sqlalchemy import create_engine,text
import pandas as pd
import numpy as np
import os

In [10]:
engine1=create_engine("mysql+pymysql://piuser:Pass%40123@localhost:3306/piit")
print(engine1)

Engine(mysql+pymysql://piuser:***@localhost:3306/piit)

In [11]:
def q(sql,**params):
    with engine1.connect () as conn:
        return pd.read_sql(text,(sql),conn,params=params)

In [13]:
def q(sql,**params):
    with engine1.connect () as conn:
8        return pd.read_sql(text(sql),conn,params=params)

In [14]:
q("show tables")

       Tables_in_piit
0             authors
1               books
2           crimedata
3         departments
4   employee_earnings
5           employees
6              evdata
7      exceldatafile1
8              mtcars
9            obisdata
10         piitstdata
11           students
12          students2
13              team1

In [19]:
file_path=("C:/analytics/data/Evdata.csv")
print (file_path)

C:/analytics/data/Evdata.csv

In [20]:
df=pd.read_csv(file_path)
df.head()

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,WA1E2AFY8R,Thurston,Olympia,WA,98512.0,2024,AUDI,Q5 E,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,23.0,0.0,22.0,263239938,POINT (-122.90787 46.9461),PUGET SOUND ENERGY INC,5.306701e+10
1,WAUUPBFF4J,Yakima,Wapato,WA,98951.0,2018,AUDI,A3,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,16.0,0.0,15.0,318160860,POINT (-120.42083 46.44779),PACIFICORP,5.307794e+10
2,1N4AZ0CP0F,King,Seattle,WA,98125.0,2015,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,84.0,0.0,46.0,184963586,POINT (-122.30253 47.72656),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303300e+10
3,WA1VAAGE5K,King,Kent,WA,98031.0,2019,AUDI,E-TRON,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,204.0,0.0,11.0,259426821,POINT (-122.17743 47.41185),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303303e+10
4,7SAXCAE57N,Snohomish,Bothell,WA,98021.0,2022,TESLA,MODEL X,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,0.0,1.0,208182236,POINT (-122.18384 47.8031),PUGET SOUND ENERGY INC,5.306105e+10

In [21]:
q("show tables")

       Tables_in_piit
0             authors
1               books
2           crimedata
3         departments
4   employee_earnings
5           employees
6              evdata
7      exceldatafile1
8              mtcars
9            obisdata
10         piitstdata
11           students
12          students2
13              team1

In [22]:
q("select * from evdata limit 10")

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,WA1E2AFY8R,Thurston,Olympia,WA,98512.0,2024,AUDI,Q5 E,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,23.0,0.0,22.0,263239938,POINT (-122.90787 46.9461),PUGET SOUND ENERGY INC,5.306701e+10
1,WAUUPBFF4J,Yakima,Wapato,WA,98951.0,2018,AUDI,A3,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,16.0,0.0,15.0,318160860,POINT (-120.42083 46.44779),PACIFICORP,5.307794e+10
2,1N4AZ0CP0F,King,Seattle,WA,98125.0,2015,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,84.0,0.0,46.0,184963586,POINT (-122.30253 47.72656),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303300e+10
3,WA1VAAGE5K,King,Kent,WA,98031.0,2019,AUDI,E-TRON,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,204.0,0.0,11.0,259426821,POINT (-122.17743 47.41185),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303303e+10
4,7SAXCAE57N,Snohomish,Bothell,WA,98021.0,2022,TESLA,MODEL X,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,0.0,1.0,208182236,POINT (-122.18384 47.8031),PUGET SOUND ENERGY INC,5.306105e+10
5,KNDJP3AEXG,Snohomish,Lynnwood,WA,98037.0,2016,KIA,SOUL,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,93.0,31950.0,21.0,209171889,POINT (-122.27734 47.83785),PUGET SOUND ENERGY INC,5.306105e+10
6,1N4AZ1CP7K,Snohomish,Edmonds,WA,98026.0,2019,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,150.0,0.0,32.0,478448624,POINT (-122.31768 47.87166),PUGET SOUND ENERGY INC,5.306105e+10
7,KNDCC3LG4L,Snohomish,Brier,WA,98036.0,2020,KIA,NIRO,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,239.0,0.0,1.0,281365724,POINT (-122.29245 47.82557),PUGET SOUND ENERGY INC,5.306105e+10
8,KM8JFDD27S,Kitsap,Bremerton,WA,98311.0,2025,HYUNDAI,TUCSON,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,32.0,0.0,23.0,281377456,POINT (-122.60915 47.62631),PUGET SOUND ENERGY INC,5.303509e+10
9,1C4JJXR6XM,Sauk,Spring Green,WI,53588.0,2021,JEEP,WRANGLER,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,21.0,0.0,NaN,182273605,POINT (-90.06403 43.17838),NON WASHINGTON STATE ELECTRIC UTILITY,5.511100e+10

In [23]:
q("select * from mtcars limit 10")

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,make_year,brand_name
0,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,None,None
1,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,None,None
2,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,None,None
3,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,None,None
4,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,None,None
5,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,None,None
6,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,None,None
7,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,None,None
8,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,None,None
9,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,None,None

In [24]:
q("select mpg,cyl,disp from mtcars")

     mpg  cyl   disp
0   21.0    6  160.0
1   21.0    6  160.0
2   22.8    4  108.0
3   21.4    6  258.0
4   18.7    8  360.0
5   18.1    6  225.0
6   14.3    8  360.0
7   24.4    4  146.7
8   22.8    4  140.8
9   19.2    6  167.6
10  17.8    6  167.6
11  16.4    8  275.8
12  17.3    8  275.8
13  15.2    8  275.8
14  10.4    8  472.0
15  10.4    8  460.0
16  14.7    8  440.0
17  32.4    4   78.7
18  30.4    4   75.7
19  33.9    4   71.1
20  21.5    4  120.1
21  15.5    8  318.0
22  15.2    8  304.0
23  13.3    8  350.0
24  19.2    8  400.0
25  27.3    4   79.0
26  26.0    4  120.3
27  30.4    4   95.1
28  15.8    8  351.0
29  19.7    6  145.0
30  15.0    8  301.0
31  21.4    4  121.0

In [33]:
import pandas as pd
import numpy as np
from pydataset import data
import plotly.express as px

In [35]:
df= data("mtcars")
df.head(5)

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [39]:
df.describe(include='all')

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [40]:
df.columns

Index(['mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear',
       'carb'],
      dtype='object')

In [41]:
df.index

Index(['Mazda RX4', 'Mazda RX4 Wag', 'Datsun 710', 'Hornet 4 Drive',
       'Hornet Sportabout', 'Valiant', 'Duster 360', 'Merc 240D', 'Merc 230',
       'Merc 280', 'Merc 280C', 'Merc 450SE', 'Merc 450SL', 'Merc 450SLC',
       'Cadillac Fleetwood', 'Lincoln Continental', 'Chrysler Imperial',
       'Fiat 128', 'Honda Civic', 'Toyota Corolla', 'Toyota Corona',
       'Dodge Challenger', 'AMC Javelin', 'Camaro Z28', 'Pontiac Firebird',
       'Fiat X1-9', 'Porsche 914-2', 'Lotus Europa', 'Ford Pantera L',
       'Ferrari Dino', 'Maserati Bora', 'Volvo 142E'],
      dtype='object')

In [43]:
df.nunique()

mpg     25
cyl      3
disp    27
hp      22
drat    22
wt      29
qsec    30
vs       2
am       2
gear     3
carb     6
dtype: int64

In [45]:
df.gear.value_counts

<bound method IndexOpsMixin.value_counts of Mazda RX4              4
Mazda RX4 Wag          4
Datsun 710             4
Hornet 4 Drive         3
Hornet Sportabout      3
Valiant                3
Duster 360             3
Merc 240D              4
Merc 230               4
Merc 280               4
Merc 280C              4
Merc 450SE             3
Merc 450SL             3
Merc 450SLC            3
Cadillac Fleetwood     3
Lincoln Continental    3
Chrysler Imperial      3
Fiat 128               4
Honda Civic            4
Toyota Corolla         4
Toyota Corona          3
Dodge Challenger       3
AMC Javelin            3
Camaro Z28             3
Pontiac Firebird       3
Fiat X1-9              4
Porsche 914-2          5
Lotus Europa           5
Ford Pantera L         5
Ferrari Dino           5
Maserati Bora          5
Volvo 142E             4
Name: gear, dtype: int64>

In [46]:
df['mpg']

Mazda RX4              21.0
Mazda RX4 Wag          21.0
Datsun 710             22.8
Hornet 4 Drive         21.4
Hornet Sportabout      18.7
Valiant                18.1
Duster 360             14.3
Merc 240D              24.4
Merc 230               22.8
Merc 280               19.2
Merc 280C              17.8
Merc 450SE             16.4
Merc 450SL             17.3
Merc 450SLC            15.2
Cadillac Fleetwood     10.4
Lincoln Continental    10.4
Chrysler Imperial      14.7
Fiat 128               32.4
Honda Civic            30.4
Toyota Corolla         33.9
Toyota Corona          21.5
Dodge Challenger       15.5
AMC Javelin            15.2
Camaro Z28             13.3
Pontiac Firebird       19.2
Fiat X1-9              27.3
Porsche 914-2          26.0
Lotus Europa           30.4
Ford Pantera L         15.8
Ferrari Dino           19.7
Maserati Bora          15.0
Volvo 142E             21.4
Name: mpg, dtype: float64

In [48]:
df[['mpg','wt']]

                      mpg     wt
Mazda RX4            21.0  2.620
Mazda RX4 Wag        21.0  2.875
Datsun 710           22.8  2.320
Hornet 4 Drive       21.4  3.215
Hornet Sportabout    18.7  3.440
Valiant              18.1  3.460
Duster 360           14.3  3.570
Merc 240D            24.4  3.190
Merc 230             22.8  3.150
Merc 280             19.2  3.440
Merc 280C            17.8  3.440
Merc 450SE           16.4  4.070
Merc 450SL           17.3  3.730
Merc 450SLC          15.2  3.780
Cadillac Fleetwood   10.4  5.250
Lincoln Continental  10.4  5.424
Chrysler Imperial    14.7  5.345
Fiat 128             32.4  2.200
Honda Civic          30.4  1.615
Toyota Corolla       33.9  1.835
Toyota Corona        21.5  2.465
Dodge Challenger     15.5  3.520
AMC Javelin          15.2  3.435
Camaro Z28           13.3  3.840
Pontiac Firebird     19.2  3.845
Fiat X1-9            27.3  1.935
Porsche 914-2        26.0  2.140
Lotus Europa         30.4  1.513
Ford Pantera L       15.8  3.170
Ferrari Dino         19.7  2.770
Maserati Bora        15.0  3.570
Volvo 142E           21.4  2.780

In [49]:
df.corr()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
mpg,1.000000,-0.852162,-0.847551,-0.776168,0.681172,-0.867659,0.418684,0.664039,0.599832,0.480285,-0.550925
cyl,-0.852162,1.000000,0.902033,0.832447,-0.699938,0.782496,-0.591242,-0.810812,-0.522607,-0.492687,0.526988
disp,-0.847551,0.902033,1.000000,0.790949,-0.710214,0.887980,-0.433698,-0.710416,-0.591227,-0.555569,0.394977
hp,-0.776168,0.832447,0.790949,1.000000,-0.448759,0.658748,-0.708223,-0.723097,-0.243204,-0.125704,0.749812
drat,0.681172,-0.699938,-0.710214,-0.448759,1.000000,-0.712441,0.091205,0.440278,0.712711,0.699610,-0.090790
wt,-0.867659,0.782496,0.887980,0.658748,-0.712441,1.000000,-0.174716,-0.554916,-0.692495,-0.583287,0.427606
qsec,0.418684,-0.591242,-0.433698,-0.708223,0.091205,-0.174716,1.000000,0.744535,-0.229861,-0.212682,-0.656249
vs,0.664039,-0.810812,-0.710416,-0.723097,0.440278,-0.554916,0.744535,1.000000,0.168345,0.206023,-0.569607
am,0.599832,-0.522607,-0.591227,-0.243204,0.712711,-0.692495,-0.229861,0.168345,1.000000,0.794059,0.057534
gear,0.480285,-0.492687,-0.555569,-0.125704,0.699610,-0.583287,-0.212682,0.206023,0.794059,1.000000,0.274073
carb,-0.550925,0.526988,0.394977,0.749812,-0.090790,0.427606,-0.656249,-0.569607,0.057534,0.274073,1.000000

In [50]:
df.mean()

mpg      20.090625
cyl       6.187500
disp    230.721875
hp      146.687500
drat      3.596563
wt        3.217250
qsec     17.848750
vs        0.437500
am        0.406250
gear      3.687500
carb      2.812500
dtype: float64

In [52]:
df.shape

(32, 11)

In [53]:
df.dtypes

mpg     float64
cyl       int64
disp    float64
hp        int64
drat    float64
wt      float64
qsec    float64
vs        int64
am        int64
gear      int64
carb      int64
dtype: object