In [2]:
import pandas as pd
import pymysql
from sqlalchemy import create_engine
import os

In [5]:
file_path = 'C:/analytics/data/students2.csv'
print (file_path)

C:/analytics/data/students2.csv

In [6]:
df=pd.read_csv(file_path)
df.head()

   rollno      name  gender         dob  height program
0       1  Jugurtha    Male  2000-08-16     156     BCA
1       2  Amandeep  Female  2000-02-21     170     BBA
2       3    Barkat  Female  2001-07-17     158     BCA
3       4    Suroor  Female  2001-11-16     188     BBA
4       5   Sultana    Male  2001-04-02     167     BCA

In [9]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import os

In [11]:
import pandas as pd
from sqlalchemy import create_engine
import os

In [13]:
file_path = 'C:/analytics/data/students2.csv'
print (file_path)

C:/analytics/data/students2.csv

In [14]:
df=pd.read_csv(file_path)
df.head(10)

   rollno      name  gender         dob  height program
0       1  Jugurtha    Male  2000-08-16     156     BCA
1       2  Amandeep  Female  2000-02-21     170     BBA
2       3    Barkat  Female  2001-07-17     158     BCA
3       4    Suroor  Female  2001-11-16     188     BBA
4       5   Sultana    Male  2001-04-02     167     BCA
5       6    Sajjad    Male  2000-10-12     153     BCA
6       7    Sharan    Male  2000-07-28     174     BBA
7       8  Djedjiga  Female  2000-06-27     163     BCA
8       9    Bijata  Female  2002-05-14     158     BBA
9      10    Mahadi  Female  2000-03-06     175     BCA

In [2]:
import pandas as pd
from sqlalchemy import create_engine
import os

In [6]:
import pymysql

In [7]:
file_path = 'C:/analytics/data/students2.csv'
print (file_path)

C:/analytics/data/students2.csv

In [8]:
df=pd.read_csv(file_path)

In [9]:
df.head()

   rollno      name  gender         dob  height program
0       1  Jugurtha    Male  2000-08-16     156     BCA
1       2  Amandeep  Female  2000-02-21     170     BBA
2       3    Barkat  Female  2001-07-17     158     BCA
3       4    Suroor  Female  2001-11-16     188     BBA
4       5   Sultana    Male  2001-04-02     167     BCA