#Read csv file

In [13]:
import pymysql
from sqlalchemy import create_engine,text
import pandas as pd
import os

In [16]:
file_path ="C:analytics/data/mtcars.csv"
print (file_path)

C:analytics/data/mtcars.csv

In [17]:
file_path = 'C:/analytics/data/mtcars.csv'
print(file_path)

C:/analytics/data/mtcars.csv

In [18]:
df=pd.read_csv(file_path)
df.head()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [19]:
file_path = "C:/analytics/data/Evdata.csv"
print (file_path)

C:/analytics/data/Evdata.csv

In [20]:
df=pd.read_csv(file_path)

In [21]:
df.head(10)

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,WA1E2AFY8R,Thurston,Olympia,WA,98512.0,2024,AUDI,Q5 E,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,23.0,0.0,22.0,263239938,POINT (-122.90787 46.9461),PUGET SOUND ENERGY INC,5.306701e+10
1,WAUUPBFF4J,Yakima,Wapato,WA,98951.0,2018,AUDI,A3,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,16.0,0.0,15.0,318160860,POINT (-120.42083 46.44779),PACIFICORP,5.307794e+10
2,1N4AZ0CP0F,King,Seattle,WA,98125.0,2015,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,84.0,0.0,46.0,184963586,POINT (-122.30253 47.72656),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303300e+10
3,WA1VAAGE5K,King,Kent,WA,98031.0,2019,AUDI,E-TRON,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,204.0,0.0,11.0,259426821,POINT (-122.17743 47.41185),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303303e+10
4,7SAXCAE57N,Snohomish,Bothell,WA,98021.0,2022,TESLA,MODEL X,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,0.0,1.0,208182236,POINT (-122.18384 47.8031),PUGET SOUND ENERGY INC,5.306105e+10
5,KNDJP3AEXG,Snohomish,Lynnwood,WA,98037.0,2016,KIA,SOUL,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,93.0,31950.0,21.0,209171889,POINT (-122.27734 47.83785),PUGET SOUND ENERGY INC,5.306105e+10
6,1N4AZ1CP7K,Snohomish,Edmonds,WA,98026.0,2019,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,150.0,0.0,32.0,478448624,POINT (-122.31768 47.87166),PUGET SOUND ENERGY INC,5.306105e+10
7,KNDCC3LG4L,Snohomish,Brier,WA,98036.0,2020,KIA,NIRO,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,239.0,0.0,1.0,281365724,POINT (-122.29245 47.82557),PUGET SOUND ENERGY INC,5.306105e+10
8,KM8JFDD27S,Kitsap,Bremerton,WA,98311.0,2025,HYUNDAI,TUCSON,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,32.0,0.0,23.0,281377456,POINT (-122.60915 47.62631),PUGET SOUND ENERGY INC,5.303509e+10
9,1C4JJXR6XM,Sauk,Spring Green,WI,53588.0,2021,JEEP,WRANGLER,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,21.0,0.0,NaN,182273605,POINT (-90.06403 43.17838),NON WASHINGTON STATE ELECTRIC UTILITY,5.511100e+10

In [24]:
df.to_csv("C:/analytics/data/Evdata5.csv")

engine1=create_engine("mysql+pymysql://piuser:Pass%40123@localhost:3306/piit")

In [39]:
print(engine1)

Engine(mysql+pymysql://piuser:***@localhost:3306/piit)

In [37]:
engine1= create_engine("mysql+pymysql://piuser:Pass%40123@localhost:3306/piit")

In [38]:
print(engine1)

Engine(mysql+pymysql://piuser:***@localhost:3306/piit)

In [34]:
def q(sql,**params):
     with engine1.connect() as conn:
        return pd.read_sql(text(sql),conn,params=params)

In [32]:
def q(sql,**params):
    with engine1.connect() as conn:
        return pd.read_sql(text(sql),conn,params=params)

In [40]:
q("show databases")

             Database
0  information_schema
1  performance_schema
2                piit

In [43]:
q("show tables")

       Tables_in_piit
0             authors
1               books
2           crimedata
3         departments
4   employee_earnings
5           employees
6              evdata
7      exceldatafile1
8              mtcars
9            obisdata
10           students
11          students2
12              team1

In [46]:
df2=pd.read_csv("C:/analytics/data/piitstdata.csv")
df2.head(10)

  rollno  english  maths  python
0   P100       79     75      66
1   P101       71     56      91
2   P102       62     69      78
3   P103       63     57      70
4   P104       81     52      98
5   P105       85     70      94
6   P106       94     60      85
7   P107       93     84      67
8   P108       59     81      61
9   P109       70     97      86

In [47]:
df2.to_sql( name='piitstdata', con=engine1, if_exists='append', index=False )

15

In [48]:
q("show tables")

       Tables_in_piit
0             authors
1               books
2           crimedata
3         departments
4   employee_earnings
5           employees
6              evdata
7      exceldatafile1
8              mtcars
9            obisdata
10         piitstdata
11           students
12          students2
13              team1

In [55]:
q("show tables")

       Tables_in_piit
0             authors
1               books
2           crimedata
3         departments
4   employee_earnings
5           employees
6              evdata
7      exceldatafile1
8              mtcars
9            obisdata
10         piitstdata
11           students
12          students2
13              team1

In [56]:
q("select * from team1")

   ser_id first_name last_name  age  Salary
0    1001    Akhansh    Mandal   26  150000
1    1002    Muhammd    Kabeer   41  150000
2    1003     Suroor     Ahmed   25  120000
3    1004   Jugartha  Halchemy   28  100000
4    1005    Nayeema    Zannat   25  100000
5    1006   Amandeep      Kaur   25  100000
6    1007    Sultana   Parveen   25  100000
7    1008     Sharan     Shaha   23  100000
8    1009     Delwar   Hossain   28  110000

In [57]:
q("select * from piitstdata")

   rollno  english  maths  python
0    P100       79     75      66
1    P101       71     56      91
2    P102       62     69      78
3    P103       63     57      70
4    P104       81     52      98
5    P105       85     70      94
6    P106       94     60      85
7    P107       93     84      67
8    P108       59     81      61
9    P109       70     97      86
10   P110       73     91      50
11   P111       70     89      64
12   P112       77     66      78
13   P113       71     70      81
14   P123       69     75      50

In [63]:
q("select * from piitstdata limit ")

  rollno  english  maths  python
0   P100       79     75      66
1   P101       71     56      91
2   P102       62     69      78
3   P103       63     57      70
4   P104       81     52      98