In [1]:
pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\users\13616\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\13616\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\13616\anaconda3\lib\site-packages (from sqlalchemy) (4.12.2)
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install pymysql

Requirement already satisfied: pymysql in c:\users\13616\anaconda3\lib\site-packages (1.1.2)Note: you may need to restart the kernel to use updated packages.

In [5]:
from sqlalchemy import create_engine,text
import pandas as pd
import os

In [6]:
engine1 = create_engine("mysql+pymysql://piuser:Pass%40123@localhost:3306/piit")
print(engine1)

Engine(mysql+pymysql://piuser:***@localhost:3306/piit)

In [7]:
def q(sql,** params):
    with engine1.connect() as conn:
        return pd.read_sql(text(),conn,params=params)

In [12]:
def q(sql, **params):
    with engine1.connect() as conn:
        return pd.read_sql(text(sql), conn, params=params)

In [14]:
q("SELECT * FROM employees")

   employee_id     name  department_id
0            1    Alice            1.0
1            2      Bob            2.0
2            3  Charlie            1.0
3            4    David            3.0
4            5      Eve            NaN

In [13]:
q("SELECT * FROM employees")

   employee_id     name  department_id
0            1    Alice            1.0
1            2      Bob            2.0
2            3  Charlie            1.0
3            4    David            3.0
4            5      Eve            NaN

In [15]:
q("SELECT * FROM team1")

   ser_id first_name last_name  age  Salary
0    1001    Akhansh    Mandal   26  150000
1    1002    Muhammd    Kabeer   41  150000
2    1003     Suroor     Ahmed   25  120000
3    1004   Jugartha  Halchemy   28  100000
4    1005    Nayeema    Zannat   25  100000
5    1006   Amandeep      Kaur   25  100000
6    1007    Sultana   Parveen   25  100000
7    1008     Sharan     Shaha   23  100000
8    1009     Delwar   Hossain   28  110000

In [16]:
q("SELECT * FROM team1 where Salary>100000 ")

   ser_id first_name last_name  age  Salary
0    1001    Akhansh    Mandal   26  150000
1    1002    Muhammd    Kabeer   41  150000
2    1003     Suroor     Ahmed   25  120000
3    1009     Delwar   Hossain   28  110000

In [17]:
q('select * from employees')

   employee_id     name  department_id
0            1    Alice            1.0
1            2      Bob            2.0
2            3  Charlie            1.0
3            4    David            3.0
4            5      Eve            NaN

In [20]:
q('select * from team1 where Salary =100000')

   ser_id first_name last_name  age  Salary
0    1004   Jugartha  Halchemy   28  100000
1    1005    Nayeema    Zannat   25  100000
2    1006   Amandeep      Kaur   25  100000
3    1007    Sultana   Parveen   25  100000
4    1008     Sharan     Shaha   23  100000

In [24]:
q('SELECT * FROM team1')

   ser_id first_name last_name  age  Salary
0    1001    Akhansh    Mandal   26  150000
1    1002    Muhammd    Kabeer   41  150000
2    1003     Suroor     Ahmed   25  120000
3    1004   Jugartha  Halchemy   28  100000
4    1005    Nayeema    Zannat   25  100000
5    1006   Amandeep      Kaur   25  100000
6    1007    Sultana   Parveen   25  100000
7    1008     Sharan     Shaha   23  100000
8    1009     Delwar   Hossain   28  110000

In [25]:
q('SELECT * FROM employees')

   employee_id     name  department_id
0            1    Alice            1.0
1            2      Bob            2.0
2            3  Charlie            1.0
3            4    David            3.0
4            5      Eve            NaN

In [27]:
q('select * from employees where employee_id <5')

   employee_id     name  department_id
0            1    Alice              1
1            2      Bob              2
2            3  Charlie              1
3            4    David              3

In [32]:
q('select * from mtcars')

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,make_year,brand_name
0,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,None,None
1,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,None,None
2,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,None,None
3,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,None,None
4,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,None,None
5,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,None,None
6,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,None,None
7,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,None,None
8,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,None,None
9,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,None,None
10,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4,None,None
11,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3,None,None
12,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3,None,None
13,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3,None,None
14,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4,None,None
15,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4,None,None
16,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4,None,None
17,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,None,None
18,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,None,None
19,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,None,None
20,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1,None,None
21,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2,None,None
22,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2,None,None
23,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4,None,None
24,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2,None,None
25,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,None,None
26,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,None,None
27,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,None,None
28,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4,None,None
29,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6,None,None
30,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8,None,None
31,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2,None,None