In [1]:
import pandas as pd 
import pandas as pd
import random
from pydataset import data

In [7]:
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [8]:
import numpy as np
import pandas as pd
from pydataset import data
import os
import matplotlib.pyplot as plt
import random
import seaborn as sns

###RANDOM
https://docs.python.org/3/library/random.html

In [11]:
print(random.random())

0.6766536790313662

In [12]:
random.randint(10, 100)

91

In [13]:
random.randrange(11, 35, 2)

27

In [14]:
random.randrange(11, 35, 2)

17

In [15]:
my_list = ['apple', 'banana', 'cherry']
random.choice(my_list)

'banana'

In [16]:
my_list = [1, 2, 3, 4, 5]
random.shuffle(my_list)
print(my_list)

[2, 1, 3, 4, 5]

In [17]:
random.sample(['red', 'blue'], counts=[6, 2], k=8)

['red', 'blue', 'red', 'blue', 'red', 'red', 'red', 'red']

In [18]:
random.sample(['Nayeema', 'Huma', 'Ratiba', 'Mohammad'], k=3)

['Nayeema', 'Huma', 'Mohammad']

In [19]:
random.choices(['HR', 'IT'], k=3)

['IT', 'IT', 'IT']

In [20]:
df = data('mtcars')
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [23]:
df.dtypes

mpg     float64
cyl       int64
disp    float64
hp        int64
drat    float64
wt      float64
qsec    float64
vs        int64
am        int64
gear      int64
carb      int64
dtype: object

In [24]:
df.describe()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [25]:

mpgvalues = df.mpg.sort_values().to_list() 
mpgvalues[0], mpgvalues[8], mpgvalues[16] , mpgvalues[24], mpgvalues[31]

(10.4, 15.5, 19.2, 22.8, 33.9)


###Functions1

In [27]:
df.mean(axis=0)

mpg      20.090625
cyl       6.187500
disp    230.721875
hp      146.687500
drat      3.596563
wt        3.217250
qsec     17.848750
vs        0.437500
am        0.406250
gear      3.687500
carb      2.812500
dtype: float64

In [28]:
df.mean(axis=1).head()

Mazda RX4            29.907273
Mazda RX4 Wag        29.981364
Datsun 710           23.598182
Hornet 4 Drive       38.739545
Hornet Sportabout    53.664545
dtype: float64

In [29]:
df.median(axis=0)

mpg      19.200
cyl       6.000
disp    196.300
hp      123.000
drat      3.695
wt        3.325
qsec     17.710
vs        0.000
am        0.000
gear      4.000
carb      2.000
dtype: float64

In [30]:
x = [1,2,3,3,4,5]
x

[1, 2, 3, 3, 4, 5]

In [31]:
np.median(x)

np.float64(3.0)

In [32]:
random.shuffle(x)
x

[5, 4, 3, 1, 2, 3]

In [33]:
np.median(x)

np.float64(3.0)

###MODE - max freq

In [34]:
from scipy import stats

In [36]:
df.mode() #pandas mode
# categorical cols - am, vs, carb, gear, cyl
# numerical cols - mpg, wt, hp, drat, qsec, disp

    mpg  cyl   disp     hp  drat    wt   qsec   vs   am  gear  carb
0  10.4  8.0  275.8  110.0  3.07  3.44  17.02  0.0  0.0   3.0   2.0
1  15.2  NaN    NaN  175.0  3.92   NaN  18.90  NaN  NaN   NaN   4.0
2  19.2  NaN    NaN  180.0   NaN   NaN    NaN  NaN  NaN   NaN   NaN
3  21.0  NaN    NaN    NaN   NaN   NaN    NaN  NaN  NaN   NaN   NaN
4  21.4  NaN    NaN    NaN   NaN   NaN    NaN  NaN  NaN   NaN   NaN
5  22.8  NaN    NaN    NaN   NaN   NaN    NaN  NaN  NaN   NaN   NaN
6  30.4  NaN    NaN    NaN   NaN   NaN    NaN  NaN  NaN   NaN   NaN

In [37]:
df.gear.value_counts()

gear
3    15
4    12
5     5
Name: count, dtype: int64

In [38]:
df.carb.value_counts()

carb
4    10
2    10
1     7
3     3
6     1
8     1
Name: count, dtype: int64

In [40]:
df.cyl.mode()

0    8
Name: cyl, dtype: int64

In [41]:
df.cyl.value_counts()

cyl
8    14
4    11
6     7
Name: count, dtype: int64

In [42]:
import statistics as stats  #note same module in scipy
x1 = [1, 2, 2, 3, 4, 4, 4, 5,5,5,5]
x1

[1, 2, 2, 3, 4, 4, 4, 5, 5, 5, 5]

In [43]:
max(set(x1), key= x1.count)

5

In [44]:
print('Mode of list is ', stats.mode(x1))  # error if tie, more than 1 mode

Mode of list is  5

In [45]:
print('Multi Mode of list is ', stats.multimode(x1))

Multi Mode of list is  [5]

In [46]:
x2 = [1,1,2,2,3]
print(x2, ' : Multi Mode of list is ', stats.multimode(x2))

[1, 1, 2, 2, 3]  : Multi Mode of list is  [1, 2]

Functions2
min
max
range
count
quantile/ quartile
IQR
std
var

In [47]:
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [48]:
df.describe()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [50]:
df[['mpg','wt']].max() #default axis=0 max

mpg    33.900
wt      5.424
dtype: float64

In [54]:
df[['mpg','wt']].min(axis=0)

mpg    10.400
wt      1.513
dtype: float64

range

df[['mpg','wt']].max() - df[['mpg','wt']].min()

In [55]:
df[['mpg','wt']].max() - df[['mpg','wt']].min()

mpg    23.500
wt      3.911
dtype: float64

In [56]:
x3 = np.array([4, 8, 15, 16, 23, 42])
x3

array([ 4,  8, 15, 16, 23, 42])

In [59]:
array([ 4,  8, 15, 16, 23, 42])

NameError: name 'array' is not defined

In [60]:
np.ptp(x3)

np.int64(38)

In [61]:

df.apply(lambda col: col.max() - col.min()) #pandas

mpg      23.500
cyl       4.000
disp    400.900
hp      283.000
drat      2.170
wt        3.911
qsec      8.400
vs        1.000
am        1.000
gear      2.000
carb      7.000
dtype: float64

In [62]:
x4 = [1, 2, 2, 3, 3, 3, 4]
print(x4.count(4))   # Output: 3

1

In [63]:
from collections import Counter
x4 = [1, 2, 2, 2, 3, 3, 3, 3, 4, 5, 5, 5,5,5]
counts = Counter(x4)
print(counts)

Counter({5: 5, 3: 4, 2: 3, 1: 1, 4: 1})

In [64]:
counts.most_common(2)

[(5, 5), (3, 4)]

In [65]:
counts.most_common(1)

[(5, 5)]

In [66]:
df.gear.value_counts()

gear
3    15
4    12
5     5
Name: count, dtype: int64

In [67]:
df.describe().head(1)

        mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
count  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0

In [68]:
df.describe(include='all').loc['count']

mpg     32.0
cyl     32.0
disp    32.0
hp      32.0
drat    32.0
wt      32.0
qsec    32.0
vs      32.0
am      32.0
gear    32.0
carb    32.0
Name: count, dtype: float64

In [69]:
df.count()

mpg     32
cyl     32
disp    32
hp      32
drat    32
wt      32
qsec    32
vs      32
am      32
gear    32
carb    32
dtype: int64


quantile

In [70]:
x5 = [10, 20, 30, 40, 50, 60, 70]

In [71]:
q25 = np.quantile(x5, 0.25)
q50 = np.quantile(x5, 0.5)
q75 = np.quantile(x5, 0.75)
print(q25, q50, q75)

25.0 40.0 55.0

In [72]:
import statistics as stats
stats.median(x5)      # 40
stats.quantiles(x5, n=4)   # quartiles

[20.0, 40.0, 60.0]

In [73]:
df.describe()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [74]:
df.describe(include='all').loc[['min','25%','50%','75%','max']]

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
min,10.400,4.0,71.100,52.0,2.760,1.51300,14.5000,0.0,0.0,3.0,1.0
25%,15.425,4.0,120.825,96.5,3.080,2.58125,16.8925,0.0,0.0,3.0,2.0
50%,19.200,6.0,196.300,123.0,3.695,3.32500,17.7100,0.0,0.0,4.0,2.0
75%,22.800,8.0,326.000,180.0,3.920,3.61000,18.9000,1.0,1.0,4.0,4.0
max,33.900,8.0,472.000,335.0,4.930,5.42400,22.9000,1.0,1.0,5.0,8.0

In [75]:
from scipy import stats
import numpy as np

x6 = np.array([10, 20, 30, 40, 50, 60, 70])
q25, q50, q75 = np.percentile(x6, [25, 50, 75], method='linear')
print(q25, q50, q75)

25.0 40.0 55.0

In [76]:
np.quantile(x6, [0.25, 0.5, 0.75], method='midpoint')

array([25., 40., 55.])

IQR
difference in Q3 & Q1

In [77]:
x7= [10, 20, 30, 40, 50, 60, 70]

Q1 = np.percentile(x7, 25)
Q3 = np.percentile(x7, 75)
IQR = Q3 - Q1

print(x7, "\n Q1:", Q1, " Q3:", Q3, " IQR:", IQR)

[10, 20, 30, 40, 50, 60, 70]
 Q1: 25.0  Q3: 55.0  IQR: 30.0

In [78]:
from scipy.stats import iqr
import numpy as np

x7B = np.array([10, 20, 30, 40, 50, 60, 70])
IQR = iqr(x7B)
print(x7B, "\n IQR:", IQR)

[10 20 30 40 50 60 70]
 IQR: 30.0

In [79]:
import statistics as stats
x7C = [10, 20, 30, 40, 50, 60, 70]
q = stats.quantiles(x7C, n=4)
IQR = q[2] - q[0]
print(x7C, "\n Q[2]", q[2], "Q[0]", q[0], ":: IQR:", IQR)

[10, 20, 30, 40, 50, 60, 70]
 Q[2] 60.0 Q[0] 20.0 :: IQR: 40.0