In [1]:
###import data from csv to mysql

In [5]:
import pandas as pd
import numpy as np
import pymysql
from sqlalchemy import create_engine
import os

In [6]:
file_path = 'C:/analytics/data/students2.csv'
print(file_path)

C:/analytics/data/students2.csv

In [18]:
df=pd.read_csv(file_path)
df.head()

   rollno      name  gender         dob  height program
0       1  Jugurtha    Male  2000-08-16     156     BCA
1       2  Amandeep  Female  2000-02-21     170     BBA
2       3    Barkat  Female  2001-07-17     158     BCA
3       4    Suroor  Female  2001-11-16     188     BBA
4       5   Sultana    Male  2001-04-02     167     BCA

In [7]:
#engine = create_engine('mysql+pymysql://piuser:Pass#123@localhost:3306/piit')
engine1 = create_engine("mysql+pymysql://piuser:Pass%40123@localhost:3306/piit")
engine1

Engine(mysql+pymysql://piuser:***@localhost:3306/piit)

In [19]:
df.to_sql('students2', engine1, if_exists='append', index=False, chunksize=1000, method='multi')

30

In [22]:
df2 = pd.read_sql("SELECT * FROM students2;", engine1)
df2.head()

   rollno      name  gender         dob  height program
0       1  Jugurtha    Male  2000-08-16     156     BCA
1       2  Amandeep  Female  2000-02-21     170     BBA
2       3    Barkat  Female  2001-07-17     158     BCA
3       4    Suroor  Female  2001-11-16     188     BBA
4       5   Sultana    Male  2001-04-02     167     BCA

In [24]:
df2.to_csv('C:/analytics/data/students3.csv')