In [1]:
from pydataset import data
import pandas as pd
import numpy as np

In [2]:
print (data())

        dataset_id                                             title
0    AirPassengers       Monthly Airline Passenger Numbers 1949-1960
1          BJsales                 Sales Data with Leading Indicator
2              BOD                         Biochemical Oxygen Demand
3     Formaldehyde                     Determination of Formaldehyde
4     HairEyeColor         Hair and Eye Color of Statistics Students
..             ...                                               ...
752        VerbAgg                  Verbal Aggression item responses
753           cake                 Breakage Angle of Chocolate Cakes
754           cbpp                 Contagious bovine pleuropneumonia
755    grouseticks  Data on red grouse ticks from Elston et al. 2001
756     sleepstudy       Reaction times in a sleep deprivation study

[757 rows x 2 columns]

In [3]:
motor = data('motor')
motor.head()

   times  accel  strata    v
1    2.4    0.0       1  3.7
2    2.6   -1.3       1  3.7
3    3.2   -2.7       1  3.7
4    3.6    0.0       1  3.7
5    4.0   -2.7       1  3.7

In [4]:
movies = data('movies')

In [5]:
movies.head()

,title,year,length,budget,rating,votes,r1,r2,r3,r4,...,r9,r10,mpaa,Action,Animation,Comedy,Drama,Documentary,Romance,Short
1,$,1971,121,NaN,6.4,348,4.5,4.5,4.5,4.5,...,4.5,4.5,NaN,0,0,1,1,0,0,0
2,$1000 a Touchdown,1939,71,NaN,6.0,20,0.0,14.5,4.5,24.5,...,4.5,14.5,NaN,0,0,1,0,0,0,0
3,$21 a Day Once a Month,1941,7,NaN,8.2,5,0.0,0.0,0.0,0.0,...,24.5,24.5,NaN,0,1,0,0,0,0,1
4,"$40,000",1996,70,NaN,8.2,6,14.5,0.0,0.0,0.0,...,34.5,45.5,NaN,0,0,1,0,0,0,0
5,"$50,000 Climax Show, The",1975,71,NaN,3.4,17,24.5,4.5,0.0,14.5,...,0.0,24.5,NaN,0,0,0,0,0,0,0

In [9]:
movies.info

<bound method DataFrame.info of                           title  year  length      budget  rating  votes  \
1                             $  1971     121         NaN     6.4    348
2             $1000 a Touchdown  1939      71         NaN     6.0     20
3        $21 a Day Once a Month  1941       7         NaN     8.2      5
4                       $40,000  1996      70         NaN     8.2      6
5      $50,000 Climax Show, The  1975      71         NaN     3.4     17
...                         ...   ...     ...         ...     ...    ...
58784                 tom thumb  1958      98         NaN     6.5    274
58785               www.XXX.com  2003     105         NaN     1.1     12
58786    www.hellssoapopera.com  1999     100         NaN     6.6      5
58787                       xXx  2002     132  85000000.0     5.5  18514
58788   xXx: State of the Union  2005     101  87000000.0     3.9   1584

         r1    r2    r3    r4  ...    r9   r10   mpaa  Action  Animation  \
1       4.5   4.5   4.5   4.5  ...   4.5   4.5    NaN       0          0
2       0.0  14.5   4.5  24.5  ...   4.5  14.5    NaN       0          0
3       0.0   0.0   0.0   0.0  ...  24.5  24.5    NaN       0          1
4      14.5   0.0   0.0   0.0  ...  34.5  45.5    NaN       0          0
5      24.5   4.5   0.0  14.5  ...   0.0  24.5    NaN       0          0
...     ...   ...   ...   ...  ...   ...   ...    ...     ...        ...
58784   4.5   4.5   4.5   4.5  ...   4.5   4.5    NaN       0          1
58785  45.5   0.0   0.0   0.0  ...   0.0  24.5    NaN       0          0
58786  24.5   0.0  24.5   0.0  ...  24.5  44.5    NaN       0          0
58787   4.5   4.5   4.5   4.5  ...   4.5   4.5  PG-13       1          0
58788  24.5   4.5   4.5   4.5  ...   4.5  14.5  PG-13       1          0

       Comedy Drama  Documentary  Romance  Short
1           1     1            0        0      0
2           1     0            0        0      0
3           0     0            0        0      1
4           1     0            0        0      0
5           0     0            0        0      0
...       ...   ...          ...      ...    ...
58784       0     0            0        0      0
58785       0     1            0        1      0
58786       0     0            0        0      0
58787       0     0            0        0      0
58788       0     0            0        0      0

[58788 rows x 24 columns]>

In [10]:
movies.dtypes

title           object
year             int64
length           int64
budget         float64
rating         float64
votes            int64
r1             float64
r2             float64
r3             float64
r4             float64
r5             float64
r6             float64
r7             float64
r8             float64
r9             float64
r10            float64
mpaa            object
Action           int64
Animation        int64
Comedy           int64
Drama            int64
Documentary      int64
Romance          int64
Short            int64
dtype: object

In [13]:
movies.columns

Index(['title', 'year', 'length', 'budget', 'rating', 'votes', 'r1', 'r2',
       'r3', 'r4', 'r5', 'r6', 'r7', 'r8', 'r9', 'r10', 'mpaa', 'Action',
       'Animation', 'Comedy', 'Drama', 'Documentary', 'Romance', 'Short'],
      dtype='object')

In [15]:
movies.Drama.value_counts()

Drama
0    36977
1    21811
Name: count, dtype: int64

In [16]:
movies.budget.value_counts()

budget
1000000.0      133
3000000.0      128
5000000.0      121
2000000.0      117
10000000.0     111
              ...
2777000.0        1
1600.0           1
170000000.0      1
72500.0          1
740000.0         1
Name: count, Length: 756, dtype: int64

In [17]:
movies.Romance=='romance'

1        False
2        False
3        False
4        False
5        False
         ...
58784    False
58785    False
58786    False
58787    False
58788    False
Name: Romance, Length: 58788, dtype: bool

In [18]:
movies.groupby('Romance')

In [19]:
movies.min

<bound method DataFrame.min of                           title  year  length      budget  rating  votes  \
1                             $  1971     121         NaN     6.4    348
2             $1000 a Touchdown  1939      71         NaN     6.0     20
3        $21 a Day Once a Month  1941       7         NaN     8.2      5
4                       $40,000  1996      70         NaN     8.2      6
5      $50,000 Climax Show, The  1975      71         NaN     3.4     17
...                         ...   ...     ...         ...     ...    ...
58784                 tom thumb  1958      98         NaN     6.5    274
58785               www.XXX.com  2003     105         NaN     1.1     12
58786    www.hellssoapopera.com  1999     100         NaN     6.6      5
58787                       xXx  2002     132  85000000.0     5.5  18514
58788   xXx: State of the Union  2005     101  87000000.0     3.9   1584

         r1    r2    r3    r4  ...    r9   r10   mpaa  Action  Animation  \
1       4.5   4.5   4.5   4.5  ...   4.5   4.5    NaN       0          0
2       0.0  14.5   4.5  24.5  ...   4.5  14.5    NaN       0          0
3       0.0   0.0   0.0   0.0  ...  24.5  24.5    NaN       0          1
4      14.5   0.0   0.0   0.0  ...  34.5  45.5    NaN       0          0
5      24.5   4.5   0.0  14.5  ...   0.0  24.5    NaN       0          0
...     ...   ...   ...   ...  ...   ...   ...    ...     ...        ...
58784   4.5   4.5   4.5   4.5  ...   4.5   4.5    NaN       0          1
58785  45.5   0.0   0.0   0.0  ...   0.0  24.5    NaN       0          0
58786  24.5   0.0  24.5   0.0  ...  24.5  44.5    NaN       0          0
58787   4.5   4.5   4.5   4.5  ...   4.5   4.5  PG-13       1          0
58788  24.5   4.5   4.5   4.5  ...   4.5  14.5  PG-13       1          0

       Comedy Drama  Documentary  Romance  Short
1           1     1            0        0      0
2           1     0            0        0      0
3           0     0            0        0      1
4           1     0            0        0      0
5           0     0            0        0      0
...       ...   ...          ...      ...    ...
58784       0     0            0        0      0
58785       0     1            0        1      0
58786       0     0            0        0      0
58787       0     0            0        0      0
58788       0     0            0        0      0

[58788 rows x 24 columns]>

In [20]:
movies.max

<bound method DataFrame.max of                           title  year  length      budget  rating  votes  \
1                             $  1971     121         NaN     6.4    348
2             $1000 a Touchdown  1939      71         NaN     6.0     20
3        $21 a Day Once a Month  1941       7         NaN     8.2      5
4                       $40,000  1996      70         NaN     8.2      6
5      $50,000 Climax Show, The  1975      71         NaN     3.4     17
...                         ...   ...     ...         ...     ...    ...
58784                 tom thumb  1958      98         NaN     6.5    274
58785               www.XXX.com  2003     105         NaN     1.1     12
58786    www.hellssoapopera.com  1999     100         NaN     6.6      5
58787                       xXx  2002     132  85000000.0     5.5  18514
58788   xXx: State of the Union  2005     101  87000000.0     3.9   1584

         r1    r2    r3    r4  ...    r9   r10   mpaa  Action  Animation  \
1       4.5   4.5   4.5   4.5  ...   4.5   4.5    NaN       0          0
2       0.0  14.5   4.5  24.5  ...   4.5  14.5    NaN       0          0
3       0.0   0.0   0.0   0.0  ...  24.5  24.5    NaN       0          1
4      14.5   0.0   0.0   0.0  ...  34.5  45.5    NaN       0          0
5      24.5   4.5   0.0  14.5  ...   0.0  24.5    NaN       0          0
...     ...   ...   ...   ...  ...   ...   ...    ...     ...        ...
58784   4.5   4.5   4.5   4.5  ...   4.5   4.5    NaN       0          1
58785  45.5   0.0   0.0   0.0  ...   0.0  24.5    NaN       0          0
58786  24.5   0.0  24.5   0.0  ...  24.5  44.5    NaN       0          0
58787   4.5   4.5   4.5   4.5  ...   4.5   4.5  PG-13       1          0
58788  24.5   4.5   4.5   4.5  ...   4.5  14.5  PG-13       1          0

       Comedy Drama  Documentary  Romance  Short
1           1     1            0        0      0
2           1     0            0        0      0
3           0     0            0        0      1
4           1     0            0        0      0
5           0     0            0        0      0
...       ...   ...          ...      ...    ...
58784       0     0            0        0      0
58785       0     1            0        1      0
58786       0     0            0        0      0
58787       0     0            0        0      0
58788       0     0            0        0      0

[58788 rows x 24 columns]>

In [21]:
movies.index

Index([    1,     2,     3,     4,     5,     6,     7,     8,     9,    10,
       ...
       58779, 58780, 58781, 58782, 58783, 58784, 58785, 58786, 58787, 58788],
      dtype='int64', length=58788)

In [22]:
movies2 = movies.copy().reset_index().rename(columns={'index':'serial'})

In [23]:
movies2.head(4)

,serial,title,year,length,budget,rating,votes,r1,r2,r3,...,r9,r10,mpaa,Action,Animation,Comedy,Drama,Documentary,Romance,Short
0,1,$,1971,121,NaN,6.4,348,4.5,4.5,4.5,...,4.5,4.5,NaN,0,0,1,1,0,0,0
1,2,$1000 a Touchdown,1939,71,NaN,6.0,20,0.0,14.5,4.5,...,4.5,14.5,NaN,0,0,1,0,0,0,0
2,3,$21 a Day Once a Month,1941,7,NaN,8.2,5,0.0,0.0,0.0,...,24.5,24.5,NaN,0,1,0,0,0,0,1
3,4,"$40,000",1996,70,NaN,8.2,6,14.5,0.0,0.0,...,34.5,45.5,NaN,0,0,1,0,0,0,0

In [24]:
movies.duplicated

<bound method DataFrame.duplicated of                           title  year  length      budget  rating  votes  \
1                             $  1971     121         NaN     6.4    348
2             $1000 a Touchdown  1939      71         NaN     6.0     20
3        $21 a Day Once a Month  1941       7         NaN     8.2      5
4                       $40,000  1996      70         NaN     8.2      6
5      $50,000 Climax Show, The  1975      71         NaN     3.4     17
...                         ...   ...     ...         ...     ...    ...
58784                 tom thumb  1958      98         NaN     6.5    274
58785               www.XXX.com  2003     105         NaN     1.1     12
58786    www.hellssoapopera.com  1999     100         NaN     6.6      5
58787                       xXx  2002     132  85000000.0     5.5  18514
58788   xXx: State of the Union  2005     101  87000000.0     3.9   1584

         r1    r2    r3    r4  ...    r9   r10   mpaa  Action  Animation  \
1       4.5   4.5   4.5   4.5  ...   4.5   4.5    NaN       0          0
2       0.0  14.5   4.5  24.5  ...   4.5  14.5    NaN       0          0
3       0.0   0.0   0.0   0.0  ...  24.5  24.5    NaN       0          1
4      14.5   0.0   0.0   0.0  ...  34.5  45.5    NaN       0          0
5      24.5   4.5   0.0  14.5  ...   0.0  24.5    NaN       0          0
...     ...   ...   ...   ...  ...   ...   ...    ...     ...        ...
58784   4.5   4.5   4.5   4.5  ...   4.5   4.5    NaN       0          1
58785  45.5   0.0   0.0   0.0  ...   0.0  24.5    NaN       0          0
58786  24.5   0.0  24.5   0.0  ...  24.5  44.5    NaN       0          0
58787   4.5   4.5   4.5   4.5  ...   4.5   4.5  PG-13       1          0
58788  24.5   4.5   4.5   4.5  ...   4.5  14.5  PG-13       1          0

       Comedy Drama  Documentary  Romance  Short
1           1     1            0        0      0
2           1     0            0        0      0
3           0     0            0        0      1
4           1     0            0        0      0
5           0     0            0        0      0
...       ...   ...          ...      ...    ...
58784       0     0            0        0      0
58785       0     1            0        1      0
58786       0     0            0        0      0
58787       0     0            0        0      0
58788       0     0            0        0      0

[58788 rows x 24 columns]>

In [27]:
volcano=data('volcano')
volcano.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V52,V53,V54,V55,V56,V57,V58,V59,V60,V61
1,100,100,101,101,101,101,101,100,100,100,...,107,107,107,106,106,105,105,104,104,103
2,101,101,102,102,102,102,102,101,101,101,...,108,108,107,107,106,106,105,105,104,104
3,102,102,103,103,103,103,103,102,102,102,...,109,108,108,107,107,106,106,105,105,104
4,103,103,104,104,104,104,104,103,103,103,...,109,109,108,108,107,107,106,106,105,105
5,104,104,105,105,105,105,105,104,104,103,...,110,109,109,108,107,107,107,106,106,105

In [28]:
volcano.dtypes

V1     int64
V2     int64
V3     int64
V4     int64
V5     int64
V6     int64
V7     int64
V8     int64
V9     int64
V10    int64
V11    int64
V12    int64
V13    int64
V14    int64
V15    int64
V16    int64
V17    int64
V18    int64
V19    int64
V20    int64
V21    int64
V22    int64
V23    int64
V24    int64
V25    int64
V26    int64
V27    int64
V28    int64
V29    int64
V30    int64
V31    int64
V32    int64
V33    int64
V34    int64
V35    int64
V36    int64
V37    int64
V38    int64
V39    int64
V40    int64
V41    int64
V42    int64
V43    int64
V44    int64
V45    int64
V46    int64
V47    int64
V48    int64
V49    int64
V50    int64
V51    int64
V52    int64
V53    int64
V54    int64
V55    int64
V56    int64
V57    int64
V58    int64
V59    int64
V60    int64
V61    int64
dtype: object

In [29]:
volcano.duplicated

<bound method DataFrame.duplicated of      V1   V2   V3   V4   V5   V6   V7   V8   V9  V10  ...  V52  V53  V54  V55  \
1   100  100  101  101  101  101  101  100  100  100  ...  107  107  107  106
2   101  101  102  102  102  102  102  101  101  101  ...  108  108  107  107
3   102  102  103  103  103  103  103  102  102  102  ...  109  108  108  107
4   103  103  104  104  104  104  104  103  103  103  ...  109  109  108  108
5   104  104  105  105  105  105  105  104  104  103  ...  110  109  109  108
6   105  105  105  106  106  106  106  105  105  104  ...  110  110  109  108
7   105  106  106  107  107  107  107  106  106  105  ...  110  111  110  109
8   106  107  107  108  108  108  108  107  107  106  ...  113  112  110  110
9   107  108  108  109  109  109  109  108  108  107  ...  115  114  112  110
10  108  109  109  110  110  110  110  109  109  108  ...  117  115  113  111
11  109  110  110  111  111  111  111  110  110  110  ...  118  116  114  112
12  110  110  111  113  112  111  113  112  112  114  ...  119  117  115  113
13  110  111  113  115  114  113  114  114  115  117  ...  120  118  116  114
14  111  113  115  117  116  115  116  117  117  119  ...  123  119  117  115
15  114  115  117  117  117  118  119  119  120  121  ...  126  121  117  114
16  116  118  118  118  120  121  121  122  122  123  ...  129  125  120  115
17  118  120  120  121  122  123  124  124  125  126  ...  131  125  120  116
18  120  121  122  123  124  125  126  127  127  128  ...  134  127  121  116
19  120  122  125  126  126  127  128  129  130  130  ...  139  131  123  119
20  121  124  126  128  129  129  130  131  132  133  ...  142  136  129  123
21  122  125  127  130  130  131  133  134  135  136  ...  144  140  134  125
22  122  125  128  130  132  133  135  136  137  139  ...  145  141  136  130
23  123  126  129  131  133  135  137  138  139  141  ...  147  142  138  133
24  124  127  130  132  135  137  138  140  142  144  ...  148  144  139  134
25  123  128  131  133  136  138  140  142  144  146  ...  150  144  139  134
26  123  127  131  134  136  138  140  142  144  147  ...  152  145  139  134
27  120  124  128  131  134  137  139  142  144  146  ...  154  148  140  134
28  118  121  125  129  132  134  137  140  142  145  ...  154  149  142  135
29  117  120  121  125  129  132  135  138  140  143  ...  153  148  142  135
30  115  118  120  122  126  130  133  136  138  141  ...  154  147  141  136
31  114  116  118  120  122  127  131  133  136  138  ...  151  146  141  135
32  115  114  116  118  120  122  127  129  132  136  ...  149  144  140  134
33  113  113  114  116  118  120  122  125  129  133  ...  146  140  137  132
34  111  112  113  114  116  118  120  122  126  130  ...  143  138  134  130
35  110  112  113  113  114  116  118  120  123  127  ...  140  136  131  128
36  109  110  111  112  114  116  118  119  120  124  ...  136  130  127  124
37  108  109  111  112  114  116  117  118  120  121  ...  130  127  124  121
38  108  109  111  113  114  116  117  118  119  120  ...  128  125  122  119
39  107  108  111  112  114  115  116  117  119  120  ...  126  123  120  118
40  107  108  110  112  113  113  115  116  118  120  ...  124  121  118  116
41  107  108  109  111  113  114  116  117  119  120  ...  122  119  117  114
42  108  109  110  112  114  115  116  117  119  120  ...  121  118  115  112
43  109  110  111  113  115  116  117  118  120  121  ...  120  117  113  111
44  110  111  112  113  116  117  118  119  120  122  ...  119  117  114  111
45  111  112  113  114  116  117  118  119  120  123  ...  118  116  113  111
46  111  112  113  115  117  118  118  120  121  124  ...  117  116  114  112
47  112  113  114  116  117  118  119  120  122  124  ...  117  116  114  112
48  113  114  115  116  117  119  119  120  122  125  ...  117  115  113  111
49  113  114  115  117  118  119  120  121  123  125  ...  116  114  112  110
50  114  115  116  117  118  119  120  121  123  126  ...  116  113  111  110
51  115  116  117  118  119  120  121  121  123  126  ...  115  113  110  110
52  115  116  117  118  119  120  121  122  123  125  ...  113  111  110  109
53  114  115  116  116  118  119  120  121  122  126  ...  112  110  109  108
54  113  114  115  116  117  118  119  120  123  126  ...  110  109  108  108
55  112  113  114  115  116  117  119  120  122  126  ...  109  108  107  107
56  111  112  114  115  116  117  118  120  122  125  ...  108  107  106  108
57  111  112  113  115  115  116  117  119  121  126  ...  107  106  105  107
58  112  113  113  114  115  116  117  119  122  127  ...  106  105  105  106
59  112  113  114  114  116  117  118  120  122  128  ...  106  105  105  105
60  112  114  114  115  116  117  119  120  122  128  ...  105  103  104  104
61  113  114  115  116  116  117  118  120  123  129  ...  104  103  104  104
62  114  115  115  116  117  118  118  120  123  129  ...  103  102  104  104
63  114  115  116  117  117  119  118  120  123  128  ...  102  102  103  103
64  115  116  116  117  118  119  119  120  124  128  ...  101  102  103  103
65  115  116  117  118  118  119  120  123  125  128  ...  101  103  103  103
66  116  117  118  118  119  120  122  123  125  128  ...  100  101  101  102
67  116  117  118  119  120  121  123  124  126  128  ...  100  100  100  101
68  117  118  119  119  120  121  123  124  126  128  ...  100  100  100  100
69  117  118  119  120  120  121  123  124  125  126  ...  100  100   99   99
70  116  117  118  120  120  121  122  123  124  125  ...   99   99   99   99
71  114  115  116  117  119  119  120  121  122  123  ...   99   98   98   98
72  112  113  114  115  116  116  117  119  120  122  ...   98   98   97   97
73  109  111  112  112  113  113  113  114  116  119  ...   97   97   96   96
74  106  107  108  108  109  110  110  112  113  114  ...   96   96   96   96
75  104  105  105  106  106  107  108  108  109  109  ...   96   96   96   96
76  102  103  103  104  104  105  106  106  107  108  ...   96   96   96   96
77  101  102  103  103  104  105  105  106  106  107  ...   96   96   96   96
78  100  101  102  102  103  103  104  104  105  106  ...   96   96   96   96
79  100  101  101  102  102  103  103  104  104  105  ...   96   96   96   96
80   99  100  101  102  102  103  103  103  104  104  ...   96   96   96   96
81   99  100  100  101  101  102  102  102  103  103  ...   96   96   96   95
82   99  100  100  100  101  101  101  102  102  103  ...   95   95   95   95
83   99   99   99   99  100  100  101  101  102  102  ...   95   95   95   95
84   98   99   99   99   99  100  100  101  101  102  ...   95   95   94   94
85   98   98   98   99   99   99  100  100  101  101  ...   94   94   94   94
86   97   98   98   98   99   99   99  100  100  100  ...   94   94   94   94
87   97   97   97   98   98   99   99   99  100  100  ...   94   94   94   94

    V56  V57  V58  V59  V60  V61
1   106  105  105  104  104  103
2   106  106  105  105  104  104
3   107  106  106  105  105  104
4   107  107  106  106  105  105
5   107  107  107  106  106  105
6   108  108  107  107  106  106
7   109  108  108  107  107  106
8   109  109  108  108  107  106
9   110  109  109  108  107  107
10  110  110  109  108  107  107
11  111  110  109  108  107  106
12  111  110  109  108  107  106
13  112  110  109  108  107  105
14  113  111  110  108  106  105
15  112  110  110  108  106  104
16  111  110  110  108  106  104
17  111  110  110  108  106  104
18  112  110  110  108  106  104
19  115  111  110  108  106  105
20  118  114  110  108  108  107
21  118  115  111  110  108  107
22  119  116  112  110  108  106
23  126  121  115  110  106  105
24  128  121  115  110  106  105
25  128  121  115  110  108  107
26  127  121  115  110  109  108
27  128  121  115  110  110  109
28  128  122  116  111  110  110
29  129  123  116  113  112  110
30  130  124  117  115  112  110
31  129  124  119  116  113  110
32  128  123  118  115  112  110
33  127  121  117  113  111  110
34  125  119  116  112  110  109
35  122  118  114  110  110  109
36  120  117  113  110  110  109
37  118  115  112  110  110  109
38  117  114  110  110  109  109
39  115  112  110  110  109  109
40  114  111  110  110  109  108
41  112  110  110  109  108  107
42  110  110  110  108  107  107
43  110  110  110  108  107  107
44  110  110  109  108  107  107
45  110  110  109  108  107  106
46  110  110  108  107  106  106
47  111  109  107  106  106  105
48  110  109  106  105  105  104
49  110  108  106  105  104  104
50  110  109  106  105  104  104
51  109  107  106  105  104  104
52  109  107  106  105  104  104
53  108  106  105  105  104  104
54  107  106  105  104  104  104
55  106  105  105  104  104  103
56  105  105  104  104  103  103
57  105  104  104  104  103  103
58  105  104  104  103  103  103
59  104  104  103  103  103  102
60  104  104  103  103  102  102
61  104  103  103  102  102  101
62  103  103  102  102  101  101
63  103  102  102  102  101  100
64  102  102  102  101  100  100
65  102  102  101  100  100  100
66  102  101  100  100  100  100
67  101  100  100  100  100  100
68  100  100   99   99   99   99
69   99   99   99   99   99   98
70   99   99   98   98   98   97
71   98   98   97   97   97   97
72   97   97   97   97   97   96
73   96   96   96   96   96   96
74   96   96   96   96   96   96
75   96   96   96   96   96   96
76   96   96   96   96   96   96
77   96   96   96   96   96   96
78   96   96   96   96   96   96
79   96   96   96   96   96   95
80   96   96   96   96   95   95
81   95   95   95   95   95   95
82   95   95   95   95   95   94
83   94   94   94   94   94   94
84   94   94   94   94   94   94
85   94   94   94   94   94   94
86   94   94   94   94   94   94
87   94   94   94   94   94   94

[87 rows x 61 columns]>

In [30]:
cars=data('cars')
cars.head()

   speed  dist
1      4     2
2      4    10
3      7     4
4      7    22
5      8    16

In [31]:
presidents=data('presidents')

In [32]:
presidents.head()

      time  presidents
1  1945.00         NaN
2  1945.25        87.0
3  1945.50        82.0
4  1945.75        75.0
5  1946.00        63.0

In [33]:
presidents.info

<bound method DataFrame.info of         time  presidents
1    1945.00         NaN
2    1945.25        87.0
3    1945.50        82.0
4    1945.75        75.0
5    1946.00        63.0
6    1946.25        50.0
7    1946.50        43.0
8    1946.75        32.0
9    1947.00        35.0
10   1947.25        60.0
11   1947.50        54.0
12   1947.75        55.0
13   1948.00        36.0
14   1948.25        39.0
15   1948.50         NaN
16   1948.75         NaN
17   1949.00        69.0
18   1949.25        57.0
19   1949.50        57.0
20   1949.75        51.0
21   1950.00        45.0
22   1950.25        37.0
23   1950.50        46.0
24   1950.75        39.0
25   1951.00        36.0
26   1951.25        24.0
27   1951.50        32.0
28   1951.75        23.0
29   1952.00        25.0
30   1952.25        32.0
31   1952.50         NaN
32   1952.75        32.0
33   1953.00        59.0
34   1953.25        74.0
35   1953.50        75.0
36   1953.75        60.0
37   1954.00        71.0
38   1954.25        61.0
39   1954.50        71.0
40   1954.75        57.0
41   1955.00        71.0
42   1955.25        68.0
43   1955.50        79.0
44   1955.75        73.0
45   1956.00        76.0
46   1956.25        71.0
47   1956.50        67.0
48   1956.75        75.0
49   1957.00        79.0
50   1957.25        62.0
51   1957.50        63.0
52   1957.75        57.0
53   1958.00        60.0
54   1958.25        49.0
55   1958.50        48.0
56   1958.75        52.0
57   1959.00        57.0
58   1959.25        62.0
59   1959.50        61.0
60   1959.75        66.0
61   1960.00        71.0
62   1960.25        62.0
63   1960.50        61.0
64   1960.75        57.0
65   1961.00        72.0
66   1961.25        83.0
67   1961.50        71.0
68   1961.75        78.0
69   1962.00        79.0
70   1962.25        71.0
71   1962.50        62.0
72   1962.75        74.0
73   1963.00        76.0
74   1963.25        64.0
75   1963.50        62.0
76   1963.75        57.0
77   1964.00        80.0
78   1964.25        73.0
79   1964.50        69.0
80   1964.75        69.0
81   1965.00        71.0
82   1965.25        64.0
83   1965.50        69.0
84   1965.75        62.0
85   1966.00        63.0
86   1966.25        46.0
87   1966.50        56.0
88   1966.75        44.0
89   1967.00        44.0
90   1967.25        52.0
91   1967.50        38.0
92   1967.75        46.0
93   1968.00        36.0
94   1968.25        49.0
95   1968.50        35.0
96   1968.75        44.0
97   1969.00        59.0
98   1969.25        65.0
99   1969.50        65.0
100  1969.75        56.0
101  1970.00        66.0
102  1970.25        53.0
103  1970.50        61.0
104  1970.75        52.0
105  1971.00        51.0
106  1971.25        48.0
107  1971.50        54.0
108  1971.75        49.0
109  1972.00        49.0
110  1972.25        61.0
111  1972.50         NaN
112  1972.75         NaN
113  1973.00        68.0
114  1973.25        44.0
115  1973.50        40.0
116  1973.75        27.0
117  1974.00        28.0
118  1974.25        25.0
119  1974.50        24.0
120  1974.75        24.0>

In [37]:
presidents.columns

Index(['time', 'presidents'], dtype='object')

In [38]:
presidents.dtypes

time          float64
presidents    float64
dtype: object