## import table from mysql to jupyter

In [1]:
from sqlalchemy import create_engine,text
import pandas as pd
import os

In [2]:
engine1 = create_engine("mysql+pymysql://piuser:Pass%40123@localhost:3306/piit")
print(engine1)

Engine(mysql+pymysql://piuser:***@localhost:3306/piit)

In [5]:
def q(sql,**params):
    with engine1.connect () as conn:
        return pd.read_sql(text(sql),conn,params=params)

In [6]:
q("show tables")

      Tables_in_piit
0            authors
1              books
2        departments
3  employee_earnings
4          employees
5     exceldatafile1
6             mtcars
7           students
8          students2
9              team1

In [7]:
from sqlalchemy import create_engine,text
import pandas as pd
import os

In [9]:
engine1=create_engine("mysql+pymysql://piuser:Pass%40123@localhost:3306/piit")
print(engine1)

Engine(mysql+pymysql://piuser:***@localhost:3306/piit)

In [12]:
def q(sql,**params):
    with engine1.connect () as conn:
       return pd.read_sql(text(sql),conn,params=params)

In [13]:
q("show tables")

      Tables_in_piit
0            authors
1              books
2        departments
3  employee_earnings
4          employees
5     exceldatafile1
6             mtcars
7           students
8          students2
9              team1

In [15]:
q("select * from employee_earnings limit 10")

,the_geom,cartodb_id,the_geom_webmercator,objectid,calendar_year,quarter,last_name,first_name,title,job_code,...,overtime_gross_pay_qtd,base_gross_pay_qtd,longevity_gross_pay_qtd,post_separation_gross_pay_qtd,miscellaneous_gross_pay_qtd,employee_category,compulsory_union_code,termination_month,termination_year,public_id
0,None,1,None,2972571,2023,4,Guess,Monte,Deputy Sheriff Captain,6K06,...,NaN,-51996.95,-93.09,None,1400.00,Civil Service,B,NaN,NaN,34277
1,None,2,None,2972572,2022,4,Massi Jr,John,Police Sergeant,6A04,...,NaN,-51012.07,-4067.88,None,-4036.47,Civil Service,P,NaN,NaN,20121
2,None,3,None,2972573,2022,4,Guess,Monte,Deputy Sheriff Captain,6K06,...,NaN,-31078.69,-3698.42,None,0.00,Civil Service,B,NaN,NaN,34277
3,None,4,None,2972574,2019,4,Timms,James,Police Officer 1,6A02,...,NaN,-28578.51,-1725.40,None,-1716.09,Civil Service,P,6.0,2016.0,36785
4,None,5,None,2972575,2022,3,Mcquilkin,Charles,Firefighter,6B01,...,10636.58,-28472.37,-940.08,None,43048.77,Civil Service,F,NaN,NaN,28977
5,None,6,None,2972576,2022,4,Feinberg,Louis,Tipstaff 1 (General),T251,...,NaN,-19171.31,NaN,None,30571.62,Exempt,K,NaN,NaN,7403
6,None,7,None,2972577,2022,1,Kennedy,Sharon,Data Service Support Clerk,1D41,...,-306.82,-13386.98,-226.50,None,20163.14,Civil Service,M,NaN,NaN,33701
7,None,8,None,2972578,2019,4,Betts,Perry,Police Officer 1,6A02,...,NaN,-8579.10,-517.00,None,-514.76,Civil Service,P,NaN,NaN,20445
8,None,9,None,2972579,2025,2,Rauscher,Stephen,Firefighter,6B01,...,NaN,-6525.36,-1405.34,None,3449.37,Civil Service,F,NaN,NaN,14324
9,None,10,None,2972580,2019,4,Wallington,Michael,School Crossing Guard,6D44,...,NaN,-4868.30,NaN,None,0.00,Civil Service,G,6.0,2020.0,17787

#import csv or excel table from data folder  to jupyter

In [16]:
import pymysql
from sqlalchemy import create_engine,text
import pandas as pd
import os

In [18]:
file_path=("C://analytics/data/citydata.csv")
print (file_path)

C://analytics/data/citydata.csv

In [19]:
df = pd.read_csv(file_path)
df.shape

(808653, 24)

In [20]:
df.head ()

,the_geom,cartodb_id,the_geom_webmercator,objectid,calendar_year,quarter,last_name,first_name,title,job_code,...,overtime_gross_pay_qtd,base_gross_pay_qtd,longevity_gross_pay_qtd,post_separation_gross_pay_qtd,miscellaneous_gross_pay_qtd,employee_category,compulsory_union_code,termination_month,termination_year,public_id
0,NaN,1,NaN,2972571,2023,4,Guess,Monte,Deputy Sheriff Captain,6K06,...,NaN,-51996.95,-93.09,NaN,1400.00,Civil Service,B,NaN,NaN,34277
1,NaN,2,NaN,2972572,2022,4,Massi Jr,John,Police Sergeant,6A04,...,NaN,-51012.07,-4067.88,NaN,-4036.47,Civil Service,P,NaN,NaN,20121
2,NaN,3,NaN,2972573,2022,4,Guess,Monte,Deputy Sheriff Captain,6K06,...,NaN,-31078.69,-3698.42,NaN,0.00,Civil Service,B,NaN,NaN,34277
3,NaN,4,NaN,2972574,2019,4,Timms,James,Police Officer 1,6A02,...,NaN,-28578.51,-1725.40,NaN,-1716.09,Civil Service,P,6.0,2016.0,36785
4,NaN,5,NaN,2972575,2022,3,Mcquilkin,Charles,Firefighter,6B01,...,10636.58,-28472.37,-940.08,NaN,43048.77,Civil Service,F,NaN,NaN,28977

##export from sql to jupyter

In [23]:
import pymysql
from sqlalchemy import create_engine,text
import pandas as pd
import os

In [24]:
engine1=create_engine("mysql+pymysql://piuser:Pass%40123@localhost:3306/piit")
print(engine1)

Engine(mysql+pymysql://piuser:***@localhost:3306/piit)

In [31]:
def q(sql,**params):
    with engine1.connect() as conn:
        return pd.read_sql(text(sql),conn,params=params)

In [32]:
q("show tables")

      Tables_in_piit
0            authors
1              books
2        departments
3  employee_earnings
4          employees
5     exceldatafile1
6             mtcars
7           students
8          students2
9              team1

In [32]:
q("show tables")

      Tables_in_piit
0            authors
1              books
2        departments
3  employee_earnings
4          employees
5     exceldatafile1
6             mtcars
7           students
8          students2
9              team1

In [52]:
file_path=("C:/analytics/data/citydata.csv")
print(file_path)

C:/analytics/data/citydata.csv

In [53]:
df1=pd.read_csv(file_path)
df1.head()

,the_geom,cartodb_id,the_geom_webmercator,objectid,calendar_year,quarter,last_name,first_name,title,job_code,...,overtime_gross_pay_qtd,base_gross_pay_qtd,longevity_gross_pay_qtd,post_separation_gross_pay_qtd,miscellaneous_gross_pay_qtd,employee_category,compulsory_union_code,termination_month,termination_year,public_id
0,NaN,1,NaN,2972571,2023,4,Guess,Monte,Deputy Sheriff Captain,6K06,...,NaN,-51996.95,-93.09,NaN,1400.00,Civil Service,B,NaN,NaN,34277
1,NaN,2,NaN,2972572,2022,4,Massi Jr,John,Police Sergeant,6A04,...,NaN,-51012.07,-4067.88,NaN,-4036.47,Civil Service,P,NaN,NaN,20121
2,NaN,3,NaN,2972573,2022,4,Guess,Monte,Deputy Sheriff Captain,6K06,...,NaN,-31078.69,-3698.42,NaN,0.00,Civil Service,B,NaN,NaN,34277
3,NaN,4,NaN,2972574,2019,4,Timms,James,Police Officer 1,6A02,...,NaN,-28578.51,-1725.40,NaN,-1716.09,Civil Service,P,6.0,2016.0,36785
4,NaN,5,NaN,2972575,2022,3,Mcquilkin,Charles,Firefighter,6B01,...,10636.58,-28472.37,-940.08,NaN,43048.77,Civil Service,F,NaN,NaN,28977

In [44]:
engine1=create_engine("mysql+pymysql://piuser:Pass%40123@localhost:3306/piit")
print(engine1)

Engine(mysql+pymysql://piuser:***@localhost:3306/piit)

In [54]:
df1.to_csv('C:/analytics/data/citydata2.csv')