In [1]:
pip install pydataset

Requirement already satisfied: pydataset in c:\users\13616\anaconda3\lib\site-packages (0.2.0)
Requirement already satisfied: pandas in c:\users\13616\anaconda3\lib\site-packages (from pydataset) (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\13616\anaconda3\lib\site-packages (from pandas->pydataset) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\13616\anaconda3\lib\site-packages (from pandas->pydataset) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\13616\anaconda3\lib\site-packages (from pandas->pydataset) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\13616\anaconda3\lib\site-packages (from pandas->pydataset) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\13616\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas->pydataset) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [5]:
import pandas as pd
import numpy as np
from pydataset import data

print(data())

In [6]:
print(data())

        dataset_id                                             title
0    AirPassengers       Monthly Airline Passenger Numbers 1949-1960
1          BJsales                 Sales Data with Leading Indicator
2              BOD                         Biochemical Oxygen Demand
3     Formaldehyde                     Determination of Formaldehyde
4     HairEyeColor         Hair and Eye Color of Statistics Students
..             ...                                               ...
752        VerbAgg                  Verbal Aggression item responses
753           cake                 Breakage Angle of Chocolate Cakes
754           cbpp                 Contagious bovine pleuropneumonia
755    grouseticks  Data on red grouse ticks from Elston et al. 2001
756     sleepstudy       Reaction times in a sleep deprivation study

[757 rows x 2 columns]

In [8]:
dataset_ids= data() ['dataset_ids'].tolist()
dataset_ids_str = ','.(join dataset_ids)
print (dataset_ind)

SyntaxError: invalid syntax (2253037320.py, line 2)

In [9]:
dataset_ids = data()['dataset_id'].tolist()
# Join into a comma-separated string
dataset_ids_str = ", ".join('dataset_ids')
print(dataset_ids_str)

d, a, t, a, s, e, t, _, i, d, s

In [11]:
iris=data('iris')

In [13]:
iris.head(10)

    Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1            5.1          3.5           1.4          0.2  setosa
2            4.9          3.0           1.4          0.2  setosa
3            4.7          3.2           1.3          0.2  setosa
4            4.6          3.1           1.5          0.2  setosa
5            5.0          3.6           1.4          0.2  setosa
6            5.4          3.9           1.7          0.4  setosa
7            4.6          3.4           1.4          0.3  setosa
8            5.0          3.4           1.5          0.2  setosa
9            4.4          2.9           1.4          0.2  setosa
10           4.9          3.1           1.5          0.1  setosa

In [24]:
iris2=iris.copy().reset_index().rename(columns={'index':'Petal.Leanth'})
iris2.head(5)

   Petal.Leanth  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0             1           5.1          3.5           1.4          0.2  setosa
1             2           4.9          3.0           1.4          0.2  setosa
2             3           4.7          3.2           1.3          0.2  setosa
3             4           4.6          3.1           1.5          0.2  setosa
4             5           5.0          3.6           1.4          0.2  setosa

In [25]:
iris2=iris.copy().reset_index().rename(columns={'index':'Sepal.Leanth'})
iris2.head(10)

   Sepal.Leanth  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0             1           5.1          3.5           1.4          0.2  setosa
1             2           4.9          3.0           1.4          0.2  setosa
2             3           4.7          3.2           1.3          0.2  setosa
3             4           4.6          3.1           1.5          0.2  setosa
4             5           5.0          3.6           1.4          0.2  setosa
5             6           5.4          3.9           1.7          0.4  setosa
6             7           4.6          3.4           1.4          0.3  setosa
7             8           5.0          3.4           1.5          0.2  setosa
8             9           4.4          2.9           1.4          0.2  setosa
9            10           4.9          3.1           1.5          0.1  setosa

In [14]:
iris.index

Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
       ...
       141, 142, 143, 144, 145, 146, 147, 148, 149, 150],
      dtype='int64', length=150)

In [15]:
iris.shape

(150, 5)

In [16]:
iris.dtypes

Sepal.Length    float64
Sepal.Width     float64
Petal.Length    float64
Petal.Width     float64
Species          object
dtype: object

In [18]:
iris.columns

Index(['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width',
       'Species'],
      dtype='object')

In [19]:
mtcars=data('mtcars')
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [20]:
mtcars2=mtcars.copy().reset_index().rename(columns={'index':'cars'})
mtcars2.head(10)

,cars,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4

In [26]:
df=mtcars.copy().reset_index().rename(columns={'index':'cyl'})
df.head(5)

,cyl,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [28]:
df1=mtcars.copy.reset_column().rename(index={'index':'Hornet 4 Drive'})
df1.head(6)

AttributeError: 'function' object has no attribute 'reset_column'