In [2]:
import pandas as pd
import numpy as np
import pymysql
from sqlalchemy import create_engine
import os

In [3]:
file_path = 'C:/analytics/data/students2.csv'
print (file_path)

C:/analytics/data/students2.csv

In [4]:
df=pd.read_csv(file_path)
df.head()

   rollno      name  gender         dob  height program
0       1  Jugurtha    Male  2000-08-16     156     BCA
1       2  Amandeep  Female  2000-02-21     170     BBA
2       3    Barkat  Female  2001-07-17     158     BCA
3       4    Suroor  Female  2001-11-16     188     BBA
4       5   Sultana    Male  2001-04-02     167     BCA

In [5]:
import pandas as pd
import numpy as np
import pymysql
from sqlalchemy import create_engine
import os

In [12]:
file_path = 'C:/analytics/data/students2.csv'
print (file_path)

C:/analytics/data/students2.csv

In [13]:
df = pd.read_csv(file_path)
df.head()

   rollno      name  gender         dob  height program
0       1  Jugurtha    Male  2000-08-16     156     BCA
1       2  Amandeep  Female  2000-02-21     170     BBA
2       3    Barkat  Female  2001-07-17     158     BCA
3       4    Suroor  Female  2001-11-16     188     BBA
4       5   Sultana    Male  2001-04-02     167     BCA

In [14]:
import pandas as pd
import numpy as np 
import pymysql
from sqlalchemy import create_engine
import os

In [15]:
file_path = 'C:/analytics/data/exceldatafile2.csv'
print (file_path)

C:/analytics/data/exceldatafile2.csv

In [17]:
df = pd.read_csv(file_path)
df.head()

,Unnamed: 0,StudentID,FirstName,LastName,Gender,Class,AdmissionDate,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,0,S001,Aarav,Sharma,M,12A,2024-04-15,NaN,ASSIGN 1,NaN,NaN,NaN,NaN,Concatinate
1,1,S002,Vivaan,Verma,F,12A,2024-04-21,NaN,StudentID,FirstName,LastName,NaN,NaN,Aarav Sharma
2,2,S003,Aditya,Gupta,M,12A,2024-05-19,NaN,S001,Aarav,Sharma,NaN,NaN,Vivaan Verma
3,3,S004,Vihaan,Mehta,M,12C,2024-06-11,NaN,S002,Vivaan,Verma,NaN,NaN,Aditya Gupta
4,4,S005,Arjun,Singh,M,12C,2022-06-22,NaN,S0007,NOTFOUND,NOTFOUND,IFERROR,NaN,Vihaan Mehta

In [18]:
import pandas as pd
import numpy as np
import pymysql
from sqlalchemy import create_engine
import os

In [20]:
file_path = 'C:/analytics/data/exceldatafile1.csv'
print(file_path)

C:/analytics/data/exceldatafile1.csv

In [21]:
df = pd.read_csv(file_path)

In [22]:
df.head()

,StudentID,FirstName,LastName,Gender,Class,AdmissionDate,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,S001,Aarav,Sharma,M,12A,4/15/2024,NaN,ASSIGN 1,NaN,NaN,NaN,NaN,Concatinate
1,S002,Vivaan,Verma,F,12A,4/21/2024,NaN,StudentID,FirstName,LastName,NaN,NaN,Aarav Sharma
2,S003,Aditya,Gupta,M,12A,5/19/2024,NaN,S001,Aarav,Sharma,NaN,NaN,Vivaan Verma
3,S004,Vihaan,Mehta,M,12C,6/11/2024,NaN,S002,Vivaan,Verma,NaN,NaN,Aditya Gupta
4,S005,Arjun,Singh,M,12C,6/22/2022,NaN,S0007,NOTFOUND,NOTFOUND,IFERROR,NaN,Vihaan Mehta

In [23]:
import pandas as pd
import numpy as np
import pymysql
from sqlalchemy import create_engine
import os

In [24]:
file_path='C:/analytics/data/employees.csv'
df.head()

,StudentID,FirstName,LastName,Gender,Class,AdmissionDate,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,S001,Aarav,Sharma,M,12A,4/15/2024,NaN,ASSIGN 1,NaN,NaN,NaN,NaN,Concatinate
1,S002,Vivaan,Verma,F,12A,4/21/2024,NaN,StudentID,FirstName,LastName,NaN,NaN,Aarav Sharma
2,S003,Aditya,Gupta,M,12A,5/19/2024,NaN,S001,Aarav,Sharma,NaN,NaN,Vivaan Verma
3,S004,Vihaan,Mehta,M,12C,6/11/2024,NaN,S002,Vivaan,Verma,NaN,NaN,Aditya Gupta
4,S005,Arjun,Singh,M,12C,6/22/2022,NaN,S0007,NOTFOUND,NOTFOUND,IFERROR,NaN,Vihaan Mehta

In [25]:
engine1 = create_engine("mysql+pymysql://piuser:Pass%40123@localhost:3306/piit")

In [26]:
print(engine1)

Engine(mysql+pymysql://piuser:***@localhost:3306/piit)

In [30]:
df.to_sql('exceldatafile1', engine1,if_exists= 'append', index=False, chunksize=1000,method='multi')

40

In [29]:
df.to_sql('exceldatafile1', engine1, if_exists='append', index=False, chunksize=1000, method='multi')

40

In [31]:
df2=pd.read_sql("select * from exceldatafile1,", engine1}
df2.head()

SyntaxError: closing parenthesis '}' does not match opening parenthesis '(' (863981461.py, line 1)

In [32]:
df2 = pd.read_sql("SELECT * FROM exceldatafile1;", engine1)

In [33]:
df2.head()

,StudentID,FirstName,LastName,Gender,Class,AdmissionDate,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,S001,Aarav,Sharma,M,12A,2024-04-15,None,ASSIGN 1,None,None,None,None,Concatinate
1,S002,Vivaan,Verma,F,12A,2024-04-21,None,StudentID,FirstName,LastName,None,None,Aarav Sharma
2,S003,Aditya,Gupta,M,12A,2024-05-19,None,S001,Aarav,Sharma,None,None,Vivaan Verma
3,S004,Vihaan,Mehta,M,12C,2024-06-11,None,S002,Vivaan,Verma,None,None,Aditya Gupta
4,S005,Arjun,Singh,M,12C,2022-06-22,None,S0007,NOTFOUND,NOTFOUND,IFERROR,None,Vihaan Mehta

In [ ]:
df2.to_csv('C:/analytics/data/exceldatafile2.csv')