In [21]:
import pandas as pd
from pydataset import data
import numpy as np

In [22]:
mtcars = data('mtcars')
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [23]:
mtcars.groupby('mpg')['hp'].count()

mpg
10.4    2
13.3    1
14.3    1
14.7    1
15.0    1
15.2    2
15.5    1
15.8    1
16.4    1
17.3    1
17.8    1
18.1    1
18.7    1
19.2    2
19.7    1
21.0    2
21.4    2
21.5    1
22.8    2
24.4    1
26.0    1
27.3    1
30.4    2
32.4    1
33.9    1
Name: hp, dtype: int64

In [24]:
mtcars.groupby('mpg')['hp'].count()

mpg
10.4    2
13.3    1
14.3    1
14.7    1
15.0    1
15.2    2
15.5    1
15.8    1
16.4    1
17.3    1
17.8    1
18.1    1
18.7    1
19.2    2
19.7    1
21.0    2
21.4    2
21.5    1
22.8    2
24.4    1
26.0    1
27.3    1
30.4    2
32.4    1
33.9    1
Name: hp, dtype: int64

In [42]:
mtcars.groupby('hp')['mpg'].mean()

hp
52     30.400000
62     24.400000
65     33.900000
66     29.850000
91     26.000000
93     22.800000
95     22.800000
97     21.500000
105    18.100000
109    21.400000
110    21.133333
113    30.400000
123    18.500000
150    15.350000
175    19.200000
180    16.300000
205    10.400000
215    10.400000
230    14.700000
245    13.800000
264    15.800000
335    15.000000
Name: mpg, dtype: float64

In [26]:
mtcars.groupby('cyl')['carb'].count()

cyl
4    11
6     7
8    14
Name: carb, dtype: int64

In [27]:
mtcars.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32 entries, Mazda RX4 to Volvo 142E
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   mpg     32 non-null     float64
 1   cyl     32 non-null     int64
 2   disp    32 non-null     float64
 3   hp      32 non-null     int64
 4   drat    32 non-null     float64
 5   wt      32 non-null     float64
 6   qsec    32 non-null     float64
 7   vs      32 non-null     int64
 8   am      32 non-null     int64
 9   gear    32 non-null     int64
 10  carb    32 non-null     int64
dtypes: float64(5), int64(6)
memory usage: 3.0+ KB

In [29]:
mtcars.shape

(32, 11)

In [37]:
mtcars.dtypes

mpg     float64
cyl       int64
disp    float64
hp        int64
drat    float64
wt      float64
qsec    float64
vs        int64
am        int64
gear      int64
carb      int64
dtype: object

In [40]:
mtcars['mpg'].mean()

np.float64(20.090625000000003)

In [43]:
mtcars.groupby ('cyl')['mpg'].mean()

cyl
4    26.663636
6    19.742857
8    15.100000
Name: mpg, dtype: float64

In [44]:
mtcars.groupby ('cyl')['mpg'].count()

cyl
4    11
6     7
8    14
Name: mpg, dtype: int64

In [47]:
mtcars['mpg'].mean()

np.float64(20.090625000000003)

In [48]:
mtcars.groupby('cyl')['mpg'].mean()

cyl
4    26.663636
6    19.742857
8    15.100000
Name: mpg, dtype: float64

In [52]:
mtcars.groupby('carb')['hp'].count()

carb
1     7
2    10
3     3
4    10
6     1
8     1
Name: hp, dtype: int64

In [54]:
data()

        dataset_id                                             title
0    AirPassengers       Monthly Airline Passenger Numbers 1949-1960
1          BJsales                 Sales Data with Leading Indicator
2              BOD                         Biochemical Oxygen Demand
3     Formaldehyde                     Determination of Formaldehyde
4     HairEyeColor         Hair and Eye Color of Statistics Students
..             ...                                               ...
752        VerbAgg                  Verbal Aggression item responses
753           cake                 Breakage Angle of Chocolate Cakes
754           cbpp                 Contagious bovine pleuropneumonia
755    grouseticks  Data on red grouse ticks from Elston et al. 2001
756     sleepstudy       Reaction times in a sleep deprivation study

[757 rows x 2 columns]