In [12]:
import pandas as pd
import numpy as np
import pymysql
from sqlalchemy import create_engine
import os

In [17]:
file_path = 'C:/analystics/data/students2.csv'
print (file_path)

C:/analystics/data/students2.csv

In [18]:
file_path = 'C:/analytics/data/students2.csv'
print (file_path)

C:/analytics/data/students2.csv

In [19]:
df=pd.read_csv(file_path)
df.head()

   rollno      name  gender         dob  height program
0       1  Jugurtha    Male  2000-08-16     156     BCA
1       2  Amandeep  Female  2000-02-21     170     BBA
2       3    Barkat  Female  2001-07-17     158     BCA
3       4    Suroor  Female  2001-11-16     188     BBA
4       5   Sultana    Male  2001-04-02     167     BCA

In [21]:
df = pd.read_csv(file_path)
df.shape
df.head(5)

   rollno      name  gender         dob  height program
0       1  Jugurtha    Male  2000-08-16     156     BCA
1       2  Amandeep  Female  2000-02-21     170     BBA
2       3    Barkat  Female  2001-07-17     158     BCA
3       4    Suroor  Female  2001-11-16     188     BBA
4       5   Sultana    Male  2001-04-02     167     BCA